/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing Address
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AddressTests
    {
        // TODO uncomment below to declare an instance variable for Address
        //private Address instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Address
            //instance = new Address();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Address
        /// </summary>
        [Test]
        public void AddressInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" Address
            //Assert.IsInstanceOf(typeof(Address), instance);
        }


        /// <summary>
        /// Test the property 'AddressLines'
        /// </summary>
        [Test]
        public void AddressLinesTest()
        {
            // TODO unit test for the property 'AddressLines'
        }
        /// <summary>
        /// Test the property 'CarrierRoute'
        /// </summary>
        [Test]
        public void CarrierRouteTest()
        {
            // TODO unit test for the property 'CarrierRoute'
        }
        /// <summary>
        /// Test the property 'CityTown'
        /// </summary>
        [Test]
        public void CityTownTest()
        {
            // TODO unit test for the property 'CityTown'
        }
        /// <summary>
        /// Test the property 'Company'
        /// </summary>
        [Test]
        public void CompanyTest()
        {
            // TODO unit test for the property 'Company'
        }
        /// <summary>
        /// Test the property 'CountryCode'
        /// </summary>
        [Test]
        public void CountryCodeTest()
        {
            // TODO unit test for the property 'CountryCode'
        }
        /// <summary>
        /// Test the property 'DeliveryPoint'
        /// </summary>
        [Test]
        public void DeliveryPointTest()
        {
            // TODO unit test for the property 'DeliveryPoint'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Test]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }
        /// <summary>
        /// Test the property 'PostalCode'
        /// </summary>
        [Test]
        public void PostalCodeTest()
        {
            // TODO unit test for the property 'PostalCode'
        }
        /// <summary>
        /// Test the property 'Residential'
        /// </summary>
        [Test]
        public void ResidentialTest()
        {
            // TODO unit test for the property 'Residential'
        }
        /// <summary>
        /// Test the property 'StateProvince'
        /// </summary>
        [Test]
        public void StateProvinceTest()
        {
            // TODO unit test for the property 'StateProvince'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'TaxId'
        /// </summary>
        [Test]
        public void TaxIdTest()
        {
            // TODO unit test for the property 'TaxId'
        }
        /// <summary>
        /// Test the property 'TaxIdType'
        /// </summary>
        [Test]
        public void TaxIdTypeTest()
        {
            // TODO unit test for the property 'TaxIdType'
        }

    }

}
