/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing AddressSuggestionResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AddressSuggestionResponseTests
    {
        // TODO uncomment below to declare an instance variable for AddressSuggestionResponse
        //private AddressSuggestionResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AddressSuggestionResponse
            //instance = new AddressSuggestionResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AddressSuggestionResponse
        /// </summary>
        [Test]
        public void AddressSuggestionResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" AddressSuggestionResponse
            //Assert.IsInstanceOf(typeof(AddressSuggestionResponse), instance);
        }


        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Test]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'Suggestions'
        /// </summary>
        [Test]
        public void SuggestionsTest()
        {
            // TODO unit test for the property 'Suggestions'
        }

    }

}
