/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing AddTrackingEventsEvents
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AddTrackingEventsEventsTests
    {
        // TODO uncomment below to declare an instance variable for AddTrackingEventsEvents
        //private AddTrackingEventsEvents instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AddTrackingEventsEvents
            //instance = new AddTrackingEventsEvents();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AddTrackingEventsEvents
        /// </summary>
        [Test]
        public void AddTrackingEventsEventsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" AddTrackingEventsEvents
            //Assert.IsInstanceOf(typeof(AddTrackingEventsEvents), instance);
        }


        /// <summary>
        /// Test the property 'EventCode'
        /// </summary>
        [Test]
        public void EventCodeTest()
        {
            // TODO unit test for the property 'EventCode'
        }
        /// <summary>
        /// Test the property 'CarrierEventCode'
        /// </summary>
        [Test]
        public void CarrierEventCodeTest()
        {
            // TODO unit test for the property 'CarrierEventCode'
        }
        /// <summary>
        /// Test the property 'EventDate'
        /// </summary>
        [Test]
        public void EventDateTest()
        {
            // TODO unit test for the property 'EventDate'
        }
        /// <summary>
        /// Test the property 'EventTime'
        /// </summary>
        [Test]
        public void EventTimeTest()
        {
            // TODO unit test for the property 'EventTime'
        }
        /// <summary>
        /// Test the property 'EventTimeOffset'
        /// </summary>
        [Test]
        public void EventTimeOffsetTest()
        {
            // TODO unit test for the property 'EventTimeOffset'
        }
        /// <summary>
        /// Test the property 'EventCity'
        /// </summary>
        [Test]
        public void EventCityTest()
        {
            // TODO unit test for the property 'EventCity'
        }
        /// <summary>
        /// Test the property 'EventStateOrProvince'
        /// </summary>
        [Test]
        public void EventStateOrProvinceTest()
        {
            // TODO unit test for the property 'EventStateOrProvince'
        }
        /// <summary>
        /// Test the property 'PostalCode'
        /// </summary>
        [Test]
        public void PostalCodeTest()
        {
            // TODO unit test for the property 'PostalCode'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Test]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }

    }

}
