/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing AddTrackingEventsReferences
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AddTrackingEventsReferencesTests
    {
        // TODO uncomment below to declare an instance variable for AddTrackingEventsReferences
        //private AddTrackingEventsReferences instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AddTrackingEventsReferences
            //instance = new AddTrackingEventsReferences();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AddTrackingEventsReferences
        /// </summary>
        [Test]
        public void AddTrackingEventsReferencesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" AddTrackingEventsReferences
            //Assert.IsInstanceOf(typeof(AddTrackingEventsReferences), instance);
        }


        /// <summary>
        /// Test the property 'ReferenceType'
        /// </summary>
        [Test]
        public void ReferenceTypeTest()
        {
            // TODO unit test for the property 'ReferenceType'
        }
        /// <summary>
        /// Test the property 'ReferenceValue'
        /// </summary>
        [Test]
        public void ReferenceValueTest()
        {
            // TODO unit test for the property 'ReferenceValue'
        }
        /// <summary>
        /// Test the property 'Events'
        /// </summary>
        [Test]
        public void EventsTest()
        {
            // TODO unit test for the property 'Events'
        }

    }

}
