/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing BatteryDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BatteryDetailsTests
    {
        // TODO uncomment below to declare an instance variable for BatteryDetails
        //private BatteryDetails instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BatteryDetails
            //instance = new BatteryDetails();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BatteryDetails
        /// </summary>
        [Test]
        public void BatteryDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" BatteryDetails
            //Assert.IsInstanceOf(typeof(BatteryDetails), instance);
        }


        /// <summary>
        /// Test the property 'BatteryMaterial'
        /// </summary>
        [Test]
        public void BatteryMaterialTest()
        {
            // TODO unit test for the property 'BatteryMaterial'
        }
        /// <summary>
        /// Test the property 'BatteryPackaging'
        /// </summary>
        [Test]
        public void BatteryPackagingTest()
        {
            // TODO unit test for the property 'BatteryPackaging'
        }
        /// <summary>
        /// Test the property 'Regulatory'
        /// </summary>
        [Test]
        public void RegulatoryTest()
        {
            // TODO unit test for the property 'Regulatory'
        }

    }

}
