/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing CancelShipment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CancelShipmentTests
    {
        // TODO uncomment below to declare an instance variable for CancelShipment
        //private CancelShipment instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CancelShipment
            //instance = new CancelShipment();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CancelShipment
        /// </summary>
        [Test]
        public void CancelShipmentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" CancelShipment
            //Assert.IsInstanceOf(typeof(CancelShipment), instance);
        }


        /// <summary>
        /// Test the property 'CancelInitiator'
        /// </summary>
        [Test]
        public void CancelInitiatorTest()
        {
            // TODO unit test for the property 'CancelInitiator'
        }
        /// <summary>
        /// Test the property 'Carrier'
        /// </summary>
        [Test]
        public void CarrierTest()
        {
            // TODO unit test for the property 'Carrier'
        }
        /// <summary>
        /// Test the property 'ErrorMessages'
        /// </summary>
        [Test]
        public void ErrorMessagesTest()
        {
            // TODO unit test for the property 'ErrorMessages'
        }
        /// <summary>
        /// Test the property 'ParcelTrackingNumber'
        /// </summary>
        [Test]
        public void ParcelTrackingNumberTest()
        {
            // TODO unit test for the property 'ParcelTrackingNumber'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'TotalCarrierCharge'
        /// </summary>
        [Test]
        public void TotalCarrierChargeTest()
        {
            // TODO unit test for the property 'TotalCarrierCharge'
        }

    }

}
