/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing CarrierFacilityResponseCarrierFacilitySuggestions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CarrierFacilityResponseCarrierFacilitySuggestionsTests
    {
        // TODO uncomment below to declare an instance variable for CarrierFacilityResponseCarrierFacilitySuggestions
        //private CarrierFacilityResponseCarrierFacilitySuggestions instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CarrierFacilityResponseCarrierFacilitySuggestions
            //instance = new CarrierFacilityResponseCarrierFacilitySuggestions();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CarrierFacilityResponseCarrierFacilitySuggestions
        /// </summary>
        [Test]
        public void CarrierFacilityResponseCarrierFacilitySuggestionsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" CarrierFacilityResponseCarrierFacilitySuggestions
            //Assert.IsInstanceOf(typeof(CarrierFacilityResponseCarrierFacilitySuggestions), instance);
        }


        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Test]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'CarrierFacilityAttributes'
        /// </summary>
        [Test]
        public void CarrierFacilityAttributesTest()
        {
            // TODO unit test for the property 'CarrierFacilityAttributes'
        }
        /// <summary>
        /// Test the property 'FacilityHours'
        /// </summary>
        [Test]
        public void FacilityHoursTest()
        {
            // TODO unit test for the property 'FacilityHours'
        }
        /// <summary>
        /// Test the property 'FacilityParking'
        /// </summary>
        [Test]
        public void FacilityParkingTest()
        {
            // TODO unit test for the property 'FacilityParking'
        }

    }

}
