/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing CarrierRule
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CarrierRuleTests
    {
        // TODO uncomment below to declare an instance variable for CarrierRule
        //private CarrierRule instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CarrierRule
            //instance = new CarrierRule();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CarrierRule
        /// </summary>
        [Test]
        public void CarrierRuleInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" CarrierRule
            //Assert.IsInstanceOf(typeof(CarrierRule), instance);
        }


        /// <summary>
        /// Test the property 'ServiceId'
        /// </summary>
        [Test]
        public void ServiceIdTest()
        {
            // TODO unit test for the property 'ServiceId'
        }
        /// <summary>
        /// Test the property 'BrandedName'
        /// </summary>
        [Test]
        public void BrandedNameTest()
        {
            // TODO unit test for the property 'BrandedName'
        }
        /// <summary>
        /// Test the property 'ParcelTypeRules'
        /// </summary>
        [Test]
        public void ParcelTypeRulesTest()
        {
            // TODO unit test for the property 'ParcelTypeRules'
        }
        /// <summary>
        /// Test the property 'Parameters'
        /// </summary>
        [Test]
        public void ParametersTest()
        {
            // TODO unit test for the property 'Parameters'
        }

    }

}
