/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing CarrierFacilityResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CarrierFacilityResponseTests
    {
        // TODO uncomment below to declare an instance variable for CarrierFacilityResponse
        //private CarrierFacilityResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CarrierFacilityResponse
            //instance = new CarrierFacilityResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CarrierFacilityResponse
        /// </summary>
        [Test]
        public void CarrierFacilityResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" CarrierFacilityResponse
            //Assert.IsInstanceOf(typeof(CarrierFacilityResponse), instance);
        }


        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Test]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'Carrier'
        /// </summary>
        [Test]
        public void CarrierTest()
        {
            // TODO unit test for the property 'Carrier'
        }
        /// <summary>
        /// Test the property 'CarrierFacilityOptions'
        /// </summary>
        [Test]
        public void CarrierFacilityOptionsTest()
        {
            // TODO unit test for the property 'CarrierFacilityOptions'
        }
        /// <summary>
        /// Test the property 'CarrierFacilitySuggestions'
        /// </summary>
        [Test]
        public void CarrierFacilitySuggestionsTest()
        {
            // TODO unit test for the property 'CarrierFacilitySuggestions'
        }

    }

}
