/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing CarrierFacilityRequestAddress
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CarrierFacilityRequestAddressTests
    {
        // TODO uncomment below to declare an instance variable for CarrierFacilityRequestAddress
        //private CarrierFacilityRequestAddress instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CarrierFacilityRequestAddress
            //instance = new CarrierFacilityRequestAddress();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CarrierFacilityRequestAddress
        /// </summary>
        [Test]
        public void CarrierFacilityRequestAddressInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" CarrierFacilityRequestAddress
            //Assert.IsInstanceOf(typeof(CarrierFacilityRequestAddress), instance);
        }


        /// <summary>
        /// Test the property 'AddressLines'
        /// </summary>
        [Test]
        public void AddressLinesTest()
        {
            // TODO unit test for the property 'AddressLines'
        }
        /// <summary>
        /// Test the property 'CityTown'
        /// </summary>
        [Test]
        public void CityTownTest()
        {
            // TODO unit test for the property 'CityTown'
        }
        /// <summary>
        /// Test the property 'StateProvince'
        /// </summary>
        [Test]
        public void StateProvinceTest()
        {
            // TODO unit test for the property 'StateProvince'
        }
        /// <summary>
        /// Test the property 'CountryCode'
        /// </summary>
        [Test]
        public void CountryCodeTest()
        {
            // TODO unit test for the property 'CountryCode'
        }

    }

}
