/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing CarrierFacilityResponseFacilityHours
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CarrierFacilityResponseFacilityHoursTests
    {
        // TODO uncomment below to declare an instance variable for CarrierFacilityResponseFacilityHours
        //private CarrierFacilityResponseFacilityHours instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CarrierFacilityResponseFacilityHours
            //instance = new CarrierFacilityResponseFacilityHours();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CarrierFacilityResponseFacilityHours
        /// </summary>
        [Test]
        public void CarrierFacilityResponseFacilityHoursInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" CarrierFacilityResponseFacilityHours
            //Assert.IsInstanceOf(typeof(CarrierFacilityResponseFacilityHours), instance);
        }


        /// <summary>
        /// Test the property 'Day'
        /// </summary>
        [Test]
        public void DayTest()
        {
            // TODO unit test for the property 'Day'
        }
        /// <summary>
        /// Test the property 'FacilityTimings'
        /// </summary>
        [Test]
        public void FacilityTimingsTest()
        {
            // TODO unit test for the property 'FacilityTimings'
        }

    }

}
