/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing CarrierFacilityRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CarrierFacilityRequestTests
    {
        // TODO uncomment below to declare an instance variable for CarrierFacilityRequest
        //private CarrierFacilityRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CarrierFacilityRequest
            //instance = new CarrierFacilityRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CarrierFacilityRequest
        /// </summary>
        [Test]
        public void CarrierFacilityRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" CarrierFacilityRequest
            //Assert.IsInstanceOf(typeof(CarrierFacilityRequest), instance);
        }


        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Test]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'Carrier'
        /// </summary>
        [Test]
        public void CarrierTest()
        {
            // TODO unit test for the property 'Carrier'
        }
        /// <summary>
        /// Test the property 'CarrierFacilityOptions'
        /// </summary>
        [Test]
        public void CarrierFacilityOptionsTest()
        {
            // TODO unit test for the property 'CarrierFacilityOptions'
        }

    }

}
