/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing CarrierFacilityResponseFacilityTimings
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CarrierFacilityResponseFacilityTimingsTests
    {
        // TODO uncomment below to declare an instance variable for CarrierFacilityResponseFacilityTimings
        //private CarrierFacilityResponseFacilityTimings instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CarrierFacilityResponseFacilityTimings
            //instance = new CarrierFacilityResponseFacilityTimings();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CarrierFacilityResponseFacilityTimings
        /// </summary>
        [Test]
        public void CarrierFacilityResponseFacilityTimingsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" CarrierFacilityResponseFacilityTimings
            //Assert.IsInstanceOf(typeof(CarrierFacilityResponseFacilityTimings), instance);
        }


        /// <summary>
        /// Test the property 'ClosesAt'
        /// </summary>
        [Test]
        public void ClosesAtTest()
        {
            // TODO unit test for the property 'ClosesAt'
        }
        /// <summary>
        /// Test the property 'OpensAt'
        /// </summary>
        [Test]
        public void OpensAtTest()
        {
            // TODO unit test for the property 'OpensAt'
        }

    }

}
