/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing CommodityInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CommodityInfoTests
    {
        // TODO uncomment below to declare an instance variable for CommodityInfo
        //private CommodityInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CommodityInfo
            //instance = new CommodityInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CommodityInfo
        /// </summary>
        [Test]
        public void CommodityInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" CommodityInfo
            //Assert.IsInstanceOf(typeof(CommodityInfo), instance);
        }


        /// <summary>
        /// Test the property 'CargoAirCraft'
        /// </summary>
        [Test]
        public void CargoAirCraftTest()
        {
            // TODO unit test for the property 'CargoAirCraft'
        }
        /// <summary>
        /// Test the property 'HazardClass'
        /// </summary>
        [Test]
        public void HazardClassTest()
        {
            // TODO unit test for the property 'HazardClass'
        }
        /// <summary>
        /// Test the property 'InfectiousSubstanceContact'
        /// </summary>
        [Test]
        public void InfectiousSubstanceContactTest()
        {
            // TODO unit test for the property 'InfectiousSubstanceContact'
        }
        /// <summary>
        /// Test the property 'InnerReceptaclesQuantity'
        /// </summary>
        [Test]
        public void InnerReceptaclesQuantityTest()
        {
            // TODO unit test for the property 'InnerReceptaclesQuantity'
        }
        /// <summary>
        /// Test the property 'InnerReceptaclesQuantityUOM'
        /// </summary>
        [Test]
        public void InnerReceptaclesQuantityUOMTest()
        {
            // TODO unit test for the property 'InnerReceptaclesQuantityUOM'
        }
        /// <summary>
        /// Test the property 'PackagingGroup'
        /// </summary>
        [Test]
        public void PackagingGroupTest()
        {
            // TODO unit test for the property 'PackagingGroup'
        }
        /// <summary>
        /// Test the property 'PackagingInstructions'
        /// </summary>
        [Test]
        public void PackagingInstructionsTest()
        {
            // TODO unit test for the property 'PackagingInstructions'
        }
        /// <summary>
        /// Test the property 'Percentage'
        /// </summary>
        [Test]
        public void PercentageTest()
        {
            // TODO unit test for the property 'Percentage'
        }
        /// <summary>
        /// Test the property 'ProperShippingName'
        /// </summary>
        [Test]
        public void ProperShippingNameTest()
        {
            // TODO unit test for the property 'ProperShippingName'
        }
        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Test]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }
        /// <summary>
        /// Test the property 'QuantityUOM'
        /// </summary>
        [Test]
        public void QuantityUOMTest()
        {
            // TODO unit test for the property 'QuantityUOM'
        }
        /// <summary>
        /// Test the property 'RadioActivityDetail'
        /// </summary>
        [Test]
        public void RadioActivityDetailTest()
        {
            // TODO unit test for the property 'RadioActivityDetail'
        }
        /// <summary>
        /// Test the property 'RadioNuclideDetail'
        /// </summary>
        [Test]
        public void RadioNuclideDetailTest()
        {
            // TODO unit test for the property 'RadioNuclideDetail'
        }
        /// <summary>
        /// Test the property 'ReportableQuantity'
        /// </summary>
        [Test]
        public void ReportableQuantityTest()
        {
            // TODO unit test for the property 'ReportableQuantity'
        }
        /// <summary>
        /// Test the property 'TechnicalName'
        /// </summary>
        [Test]
        public void TechnicalNameTest()
        {
            // TODO unit test for the property 'TechnicalName'
        }
        /// <summary>
        /// Test the property 'UnId'
        /// </summary>
        [Test]
        public void UnIdTest()
        {
            // TODO unit test for the property 'UnId'
        }

    }

}
