/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing ContainerManifestResponseData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ContainerManifestResponseDataTests
    {
        // TODO uncomment below to declare an instance variable for ContainerManifestResponseData
        //private ContainerManifestResponseData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ContainerManifestResponseData
            //instance = new ContainerManifestResponseData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ContainerManifestResponseData
        /// </summary>
        [Test]
        public void ContainerManifestResponseDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ContainerManifestResponseData
            //Assert.IsInstanceOf(typeof(ContainerManifestResponseData), instance);
        }


        /// <summary>
        /// Test the property 'PbContainerId'
        /// </summary>
        [Test]
        public void PbContainerIdTest()
        {
            // TODO unit test for the property 'PbContainerId'
        }
        /// <summary>
        /// Test the property 'LabelData'
        /// </summary>
        [Test]
        public void LabelDataTest()
        {
            // TODO unit test for the property 'LabelData'
        }

    }

}
