/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing ContainerDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ContainerDetailsTests
    {
        // TODO uncomment below to declare an instance variable for ContainerDetails
        //private ContainerDetails instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ContainerDetails
            //instance = new ContainerDetails();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ContainerDetails
        /// </summary>
        [Test]
        public void ContainerDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ContainerDetails
            //Assert.IsInstanceOf(typeof(ContainerDetails), instance);
        }


        /// <summary>
        /// Test the property 'CommodityInfo'
        /// </summary>
        [Test]
        public void CommodityInfoTest()
        {
            // TODO unit test for the property 'CommodityInfo'
        }
        /// <summary>
        /// Test the property 'ContainerType'
        /// </summary>
        [Test]
        public void ContainerTypeTest()
        {
            // TODO unit test for the property 'ContainerType'
        }
        /// <summary>
        /// Test the property 'PackagingType'
        /// </summary>
        [Test]
        public void PackagingTypeTest()
        {
            // TODO unit test for the property 'PackagingType'
        }

    }

}
