/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing CrossBorderQuotesErrorsQuoteLines
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CrossBorderQuotesErrorsQuoteLinesTests
    {
        // TODO uncomment below to declare an instance variable for CrossBorderQuotesErrorsQuoteLines
        //private CrossBorderQuotesErrorsQuoteLines instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CrossBorderQuotesErrorsQuoteLines
            //instance = new CrossBorderQuotesErrorsQuoteLines();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CrossBorderQuotesErrorsQuoteLines
        /// </summary>
        [Test]
        public void CrossBorderQuotesErrorsQuoteLinesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" CrossBorderQuotesErrorsQuoteLines
            //Assert.IsInstanceOf(typeof(CrossBorderQuotesErrorsQuoteLines), instance);
        }


        /// <summary>
        /// Test the property 'LineId'
        /// </summary>
        [Test]
        public void LineIdTest()
        {
            // TODO unit test for the property 'LineId'
        }
        /// <summary>
        /// Test the property 'MerchantComRefId'
        /// </summary>
        [Test]
        public void MerchantComRefIdTest()
        {
            // TODO unit test for the property 'MerchantComRefId'
        }
        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Test]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }
        /// <summary>
        /// Test the property 'UnitErrors'
        /// </summary>
        [Test]
        public void UnitErrorsTest()
        {
            // TODO unit test for the property 'UnitErrors'
        }

    }

}
