/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing CrossBorderQuotesResponseTotalRates
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CrossBorderQuotesResponseTotalRatesTests
    {
        // TODO uncomment below to declare an instance variable for CrossBorderQuotesResponseTotalRates
        //private CrossBorderQuotesResponseTotalRates instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CrossBorderQuotesResponseTotalRates
            //instance = new CrossBorderQuotesResponseTotalRates();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CrossBorderQuotesResponseTotalRates
        /// </summary>
        [Test]
        public void CrossBorderQuotesResponseTotalRatesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" CrossBorderQuotesResponseTotalRates
            //Assert.IsInstanceOf(typeof(CrossBorderQuotesResponseTotalRates), instance);
        }


        /// <summary>
        /// Test the property 'ServiceId'
        /// </summary>
        [Test]
        public void ServiceIdTest()
        {
            // TODO unit test for the property 'ServiceId'
        }
        /// <summary>
        /// Test the property 'BaseCharge'
        /// </summary>
        [Test]
        public void BaseChargeTest()
        {
            // TODO unit test for the property 'BaseCharge'
        }
        /// <summary>
        /// Test the property 'DeliveryCommitment'
        /// </summary>
        [Test]
        public void DeliveryCommitmentTest()
        {
            // TODO unit test for the property 'DeliveryCommitment'
        }
        /// <summary>
        /// Test the property 'TotalCarrierCharge'
        /// </summary>
        [Test]
        public void TotalCarrierChargeTest()
        {
            // TODO unit test for the property 'TotalCarrierCharge'
        }
        /// <summary>
        /// Test the property 'TotalDutyAmount'
        /// </summary>
        [Test]
        public void TotalDutyAmountTest()
        {
            // TODO unit test for the property 'TotalDutyAmount'
        }
        /// <summary>
        /// Test the property 'TotalTaxAmount'
        /// </summary>
        [Test]
        public void TotalTaxAmountTest()
        {
            // TODO unit test for the property 'TotalTaxAmount'
        }

    }

}
