/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing CrossBorderQuotesRequestIdentifiers
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CrossBorderQuotesRequestIdentifiersTests
    {
        // TODO uncomment below to declare an instance variable for CrossBorderQuotesRequestIdentifiers
        //private CrossBorderQuotesRequestIdentifiers instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CrossBorderQuotesRequestIdentifiers
            //instance = new CrossBorderQuotesRequestIdentifiers();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CrossBorderQuotesRequestIdentifiers
        /// </summary>
        [Test]
        public void CrossBorderQuotesRequestIdentifiersInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" CrossBorderQuotesRequestIdentifiers
            //Assert.IsInstanceOf(typeof(CrossBorderQuotesRequestIdentifiers), instance);
        }


        /// <summary>
        /// Test the property 'Number'
        /// </summary>
        [Test]
        public void NumberTest()
        {
            // TODO unit test for the property 'Number'
        }
        /// <summary>
        /// Test the property 'Source'
        /// </summary>
        [Test]
        public void SourceTest()
        {
            // TODO unit test for the property 'Source'
        }

    }

}
