/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing CrossBorderQuotesRequestPricingCodPrice
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CrossBorderQuotesRequestPricingCodPriceTests
    {
        // TODO uncomment below to declare an instance variable for CrossBorderQuotesRequestPricingCodPrice
        //private CrossBorderQuotesRequestPricingCodPrice instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CrossBorderQuotesRequestPricingCodPrice
            //instance = new CrossBorderQuotesRequestPricingCodPrice();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CrossBorderQuotesRequestPricingCodPrice
        /// </summary>
        [Test]
        public void CrossBorderQuotesRequestPricingCodPriceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" CrossBorderQuotesRequestPricingCodPrice
            //Assert.IsInstanceOf(typeof(CrossBorderQuotesRequestPricingCodPrice), instance);
        }


        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Test]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }
        /// <summary>
        /// Test the property 'Cod'
        /// </summary>
        [Test]
        public void CodTest()
        {
            // TODO unit test for the property 'Cod'
        }
        /// <summary>
        /// Test the property 'IncludesDuty'
        /// </summary>
        [Test]
        public void IncludesDutyTest()
        {
            // TODO unit test for the property 'IncludesDuty'
        }
        /// <summary>
        /// Test the property 'IncludesTaxes'
        /// </summary>
        [Test]
        public void IncludesTaxesTest()
        {
            // TODO unit test for the property 'IncludesTaxes'
        }

    }

}
