/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing CrossBorderQuotesRequestBasketItems
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CrossBorderQuotesRequestBasketItemsTests
    {
        // TODO uncomment below to declare an instance variable for CrossBorderQuotesRequestBasketItems
        //private CrossBorderQuotesRequestBasketItems instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CrossBorderQuotesRequestBasketItems
            //instance = new CrossBorderQuotesRequestBasketItems();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CrossBorderQuotesRequestBasketItems
        /// </summary>
        [Test]
        public void CrossBorderQuotesRequestBasketItemsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" CrossBorderQuotesRequestBasketItems
            //Assert.IsInstanceOf(typeof(CrossBorderQuotesRequestBasketItems), instance);
        }


        /// <summary>
        /// Test the property 'ItemId'
        /// </summary>
        [Test]
        public void ItemIdTest()
        {
            // TODO unit test for the property 'ItemId'
        }
        /// <summary>
        /// Test the property 'Categories'
        /// </summary>
        [Test]
        public void CategoriesTest()
        {
            // TODO unit test for the property 'Categories'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'LongDescription'
        /// </summary>
        [Test]
        public void LongDescriptionTest()
        {
            // TODO unit test for the property 'LongDescription'
        }
        /// <summary>
        /// Test the property 'UnitWeight'
        /// </summary>
        [Test]
        public void UnitWeightTest()
        {
            // TODO unit test for the property 'UnitWeight'
        }
        /// <summary>
        /// Test the property 'ItemDimension'
        /// </summary>
        [Test]
        public void ItemDimensionTest()
        {
            // TODO unit test for the property 'ItemDimension'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Test]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }
        /// <summary>
        /// Test the property 'UnitPrice'
        /// </summary>
        [Test]
        public void UnitPriceTest()
        {
            // TODO unit test for the property 'UnitPrice'
        }
        /// <summary>
        /// Test the property 'OriginCountryCode'
        /// </summary>
        [Test]
        public void OriginCountryCodeTest()
        {
            // TODO unit test for the property 'OriginCountryCode'
        }
        /// <summary>
        /// Test the property 'ParentIdentifier'
        /// </summary>
        [Test]
        public void ParentIdentifierTest()
        {
            // TODO unit test for the property 'ParentIdentifier'
        }
        /// <summary>
        /// Test the property 'ChildIdentifier'
        /// </summary>
        [Test]
        public void ChildIdentifierTest()
        {
            // TODO unit test for the property 'ChildIdentifier'
        }
        /// <summary>
        /// Test the property 'Kit'
        /// </summary>
        [Test]
        public void KitTest()
        {
            // TODO unit test for the property 'Kit'
        }
        /// <summary>
        /// Test the property 'KitIdentifier'
        /// </summary>
        [Test]
        public void KitIdentifierTest()
        {
            // TODO unit test for the property 'KitIdentifier'
        }
        /// <summary>
        /// Test the property 'KitQuantity'
        /// </summary>
        [Test]
        public void KitQuantityTest()
        {
            // TODO unit test for the property 'KitQuantity'
        }
        /// <summary>
        /// Test the property 'Manufacturer'
        /// </summary>
        [Test]
        public void ManufacturerTest()
        {
            // TODO unit test for the property 'Manufacturer'
        }
        /// <summary>
        /// Test the property 'Brand'
        /// </summary>
        [Test]
        public void BrandTest()
        {
            // TODO unit test for the property 'Brand'
        }
        /// <summary>
        /// Test the property 'Eccn'
        /// </summary>
        [Test]
        public void EccnTest()
        {
            // TODO unit test for the property 'Eccn'
        }
        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Test]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }
        /// <summary>
        /// Test the property 'Pricing'
        /// </summary>
        [Test]
        public void PricingTest()
        {
            // TODO unit test for the property 'Pricing'
        }
        /// <summary>
        /// Test the property 'HSTariffCode'
        /// </summary>
        [Test]
        public void HSTariffCodeTest()
        {
            // TODO unit test for the property 'HSTariffCode'
        }
        /// <summary>
        /// Test the property 'HSTariffCodeCountry'
        /// </summary>
        [Test]
        public void HSTariffCodeCountryTest()
        {
            // TODO unit test for the property 'HSTariffCodeCountry'
        }
        /// <summary>
        /// Test the property 'Identifiers'
        /// </summary>
        [Test]
        public void IdentifiersTest()
        {
            // TODO unit test for the property 'Identifiers'
        }
        /// <summary>
        /// Test the property 'ImageUrls'
        /// </summary>
        [Test]
        public void ImageUrlsTest()
        {
            // TODO unit test for the property 'ImageUrls'
        }
        /// <summary>
        /// Test the property 'ShipsAlone'
        /// </summary>
        [Test]
        public void ShipsAloneTest()
        {
            // TODO unit test for the property 'ShipsAlone'
        }
        /// <summary>
        /// Test the property 'Attributes'
        /// </summary>
        [Test]
        public void AttributesTest()
        {
            // TODO unit test for the property 'Attributes'
        }
        /// <summary>
        /// Test the property 'Hazmats'
        /// </summary>
        [Test]
        public void HazmatsTest()
        {
            // TODO unit test for the property 'Hazmats'
        }

    }

}
