/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing CrossBorderQuotesErrorsQuote
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CrossBorderQuotesErrorsQuoteTests
    {
        // TODO uncomment below to declare an instance variable for CrossBorderQuotesErrorsQuote
        //private CrossBorderQuotesErrorsQuote instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CrossBorderQuotesErrorsQuote
            //instance = new CrossBorderQuotesErrorsQuote();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CrossBorderQuotesErrorsQuote
        /// </summary>
        [Test]
        public void CrossBorderQuotesErrorsQuoteInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" CrossBorderQuotesErrorsQuote
            //Assert.IsInstanceOf(typeof(CrossBorderQuotesErrorsQuote), instance);
        }


        /// <summary>
        /// Test the property 'QuoteCurrency'
        /// </summary>
        [Test]
        public void QuoteCurrencyTest()
        {
            // TODO unit test for the property 'QuoteCurrency'
        }
        /// <summary>
        /// Test the property 'QuoteLines'
        /// </summary>
        [Test]
        public void QuoteLinesTest()
        {
            // TODO unit test for the property 'QuoteLines'
        }
        /// <summary>
        /// Test the property 'Errors'
        /// </summary>
        [Test]
        public void ErrorsTest()
        {
            // TODO unit test for the property 'Errors'
        }

    }

}
