/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing CrossBorderQuotesResponseQuoteLines
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CrossBorderQuotesResponseQuoteLinesTests
    {
        // TODO uncomment below to declare an instance variable for CrossBorderQuotesResponseQuoteLines
        //private CrossBorderQuotesResponseQuoteLines instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CrossBorderQuotesResponseQuoteLines
            //instance = new CrossBorderQuotesResponseQuoteLines();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CrossBorderQuotesResponseQuoteLines
        /// </summary>
        [Test]
        public void CrossBorderQuotesResponseQuoteLinesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" CrossBorderQuotesResponseQuoteLines
            //Assert.IsInstanceOf(typeof(CrossBorderQuotesResponseQuoteLines), instance);
        }


        /// <summary>
        /// Test the property 'LineId'
        /// </summary>
        [Test]
        public void LineIdTest()
        {
            // TODO unit test for the property 'LineId'
        }
        /// <summary>
        /// Test the property 'ItemId'
        /// </summary>
        [Test]
        public void ItemIdTest()
        {
            // TODO unit test for the property 'ItemId'
        }
        /// <summary>
        /// Test the property 'QuoteLineId'
        /// </summary>
        [Test]
        public void QuoteLineIdTest()
        {
            // TODO unit test for the property 'QuoteLineId'
        }
        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Test]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }
        /// <summary>
        /// Test the property 'UnitRates'
        /// </summary>
        [Test]
        public void UnitRatesTest()
        {
            // TODO unit test for the property 'UnitRates'
        }
        /// <summary>
        /// Test the property 'LineRates'
        /// </summary>
        [Test]
        public void LineRatesTest()
        {
            // TODO unit test for the property 'LineRates'
        }

    }

}
