/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing CrossBorderQuotesRequestPricing
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CrossBorderQuotesRequestPricingTests
    {
        // TODO uncomment below to declare an instance variable for CrossBorderQuotesRequestPricing
        //private CrossBorderQuotesRequestPricing instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CrossBorderQuotesRequestPricing
            //instance = new CrossBorderQuotesRequestPricing();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CrossBorderQuotesRequestPricing
        /// </summary>
        [Test]
        public void CrossBorderQuotesRequestPricingInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" CrossBorderQuotesRequestPricing
            //Assert.IsInstanceOf(typeof(CrossBorderQuotesRequestPricing), instance);
        }


        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Test]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }
        /// <summary>
        /// Test the property 'CodPrice'
        /// </summary>
        [Test]
        public void CodPriceTest()
        {
            // TODO unit test for the property 'CodPrice'
        }
        /// <summary>
        /// Test the property 'DutiableValue'
        /// </summary>
        [Test]
        public void DutiableValueTest()
        {
            // TODO unit test for the property 'DutiableValue'
        }

    }

}
