/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing CrossBorderQuotesRequestCategories
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CrossBorderQuotesRequestCategoriesTests
    {
        // TODO uncomment below to declare an instance variable for CrossBorderQuotesRequestCategories
        //private CrossBorderQuotesRequestCategories instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CrossBorderQuotesRequestCategories
            //instance = new CrossBorderQuotesRequestCategories();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CrossBorderQuotesRequestCategories
        /// </summary>
        [Test]
        public void CrossBorderQuotesRequestCategoriesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" CrossBorderQuotesRequestCategories
            //Assert.IsInstanceOf(typeof(CrossBorderQuotesRequestCategories), instance);
        }


        /// <summary>
        /// Test the property 'CategoryCode'
        /// </summary>
        [Test]
        public void CategoryCodeTest()
        {
            // TODO unit test for the property 'CategoryCode'
        }
        /// <summary>
        /// Test the property 'Descriptions'
        /// </summary>
        [Test]
        public void DescriptionsTest()
        {
            // TODO unit test for the property 'Descriptions'
        }
        /// <summary>
        /// Test the property 'ParentCategoryCode'
        /// </summary>
        [Test]
        public void ParentCategoryCodeTest()
        {
            // TODO unit test for the property 'ParentCategoryCode'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

    }

}
