/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing CrossBorderQuotesRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CrossBorderQuotesRequestTests
    {
        // TODO uncomment below to declare an instance variable for CrossBorderQuotesRequest
        //private CrossBorderQuotesRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CrossBorderQuotesRequest
            //instance = new CrossBorderQuotesRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CrossBorderQuotesRequest
        /// </summary>
        [Test]
        public void CrossBorderQuotesRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" CrossBorderQuotesRequest
            //Assert.IsInstanceOf(typeof(CrossBorderQuotesRequest), instance);
        }


        /// <summary>
        /// Test the property 'QuoteCurrency'
        /// </summary>
        [Test]
        public void QuoteCurrencyTest()
        {
            // TODO unit test for the property 'QuoteCurrency'
        }
        /// <summary>
        /// Test the property 'BasketCurrency'
        /// </summary>
        [Test]
        public void BasketCurrencyTest()
        {
            // TODO unit test for the property 'BasketCurrency'
        }
        /// <summary>
        /// Test the property 'FromAddress'
        /// </summary>
        [Test]
        public void FromAddressTest()
        {
            // TODO unit test for the property 'FromAddress'
        }
        /// <summary>
        /// Test the property 'ToAddress'
        /// </summary>
        [Test]
        public void ToAddressTest()
        {
            // TODO unit test for the property 'ToAddress'
        }
        /// <summary>
        /// Test the property 'BasketItems'
        /// </summary>
        [Test]
        public void BasketItemsTest()
        {
            // TODO unit test for the property 'BasketItems'
        }
        /// <summary>
        /// Test the property 'Rates'
        /// </summary>
        [Test]
        public void RatesTest()
        {
            // TODO unit test for the property 'Rates'
        }
        /// <summary>
        /// Test the property 'ShipmentOptions'
        /// </summary>
        [Test]
        public void ShipmentOptionsTest()
        {
            // TODO unit test for the property 'ShipmentOptions'
        }

    }

}
