/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing CustomsItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomsItemTests
    {
        // TODO uncomment below to declare an instance variable for CustomsItem
        //private CustomsItem instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CustomsItem
            //instance = new CustomsItem();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CustomsItem
        /// </summary>
        [Test]
        public void CustomsItemInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" CustomsItem
            //Assert.IsInstanceOf(typeof(CustomsItem), instance);
        }


        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'HSTariffCode'
        /// </summary>
        [Test]
        public void HSTariffCodeTest()
        {
            // TODO unit test for the property 'HSTariffCode'
        }
        /// <summary>
        /// Test the property 'NetCostMethod'
        /// </summary>
        [Test]
        public void NetCostMethodTest()
        {
            // TODO unit test for the property 'NetCostMethod'
        }
        /// <summary>
        /// Test the property 'OriginCountryCode'
        /// </summary>
        [Test]
        public void OriginCountryCodeTest()
        {
            // TODO unit test for the property 'OriginCountryCode'
        }
        /// <summary>
        /// Test the property 'OriginStateProvince'
        /// </summary>
        [Test]
        public void OriginStateProvinceTest()
        {
            // TODO unit test for the property 'OriginStateProvince'
        }
        /// <summary>
        /// Test the property 'PreferenceCriterion'
        /// </summary>
        [Test]
        public void PreferenceCriterionTest()
        {
            // TODO unit test for the property 'PreferenceCriterion'
        }
        /// <summary>
        /// Test the property 'ProducerAddress'
        /// </summary>
        [Test]
        public void ProducerAddressTest()
        {
            // TODO unit test for the property 'ProducerAddress'
        }
        /// <summary>
        /// Test the property 'ProducerDetermination'
        /// </summary>
        [Test]
        public void ProducerDeterminationTest()
        {
            // TODO unit test for the property 'ProducerDetermination'
        }
        /// <summary>
        /// Test the property 'ProducerId'
        /// </summary>
        [Test]
        public void ProducerIdTest()
        {
            // TODO unit test for the property 'ProducerId'
        }
        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Test]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }
        /// <summary>
        /// Test the property 'QuantityUOM'
        /// </summary>
        [Test]
        public void QuantityUOMTest()
        {
            // TODO unit test for the property 'QuantityUOM'
        }
        /// <summary>
        /// Test the property 'UnitPrice'
        /// </summary>
        [Test]
        public void UnitPriceTest()
        {
            // TODO unit test for the property 'UnitPrice'
        }
        /// <summary>
        /// Test the property 'UnitWeight'
        /// </summary>
        [Test]
        public void UnitWeightTest()
        {
            // TODO unit test for the property 'UnitWeight'
        }

    }

}
