/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing Customs
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomsTests
    {
        // TODO uncomment below to declare an instance variable for Customs
        //private Customs instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Customs
            //instance = new Customs();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Customs
        /// </summary>
        [Test]
        public void CustomsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" Customs
            //Assert.IsInstanceOf(typeof(Customs), instance);
        }


        /// <summary>
        /// Test the property 'CustomsInfo'
        /// </summary>
        [Test]
        public void CustomsInfoTest()
        {
            // TODO unit test for the property 'CustomsInfo'
        }
        /// <summary>
        /// Test the property 'CustomsItems'
        /// </summary>
        [Test]
        public void CustomsItemsTest()
        {
            // TODO unit test for the property 'CustomsItems'
        }

    }

}
