/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing CustomsInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomsInfoTests
    {
        // TODO uncomment below to declare an instance variable for CustomsInfo
        //private CustomsInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CustomsInfo
            //instance = new CustomsInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CustomsInfo
        /// </summary>
        [Test]
        public void CustomsInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" CustomsInfo
            //Assert.IsInstanceOf(typeof(CustomsInfo), instance);
        }


        /// <summary>
        /// Test the property 'EELPFC'
        /// </summary>
        [Test]
        public void EELPFCTest()
        {
            // TODO unit test for the property 'EELPFC'
        }
        /// <summary>
        /// Test the property 'BlanketEndDate'
        /// </summary>
        [Test]
        public void BlanketEndDateTest()
        {
            // TODO unit test for the property 'BlanketEndDate'
        }
        /// <summary>
        /// Test the property 'BlanketStartDate'
        /// </summary>
        [Test]
        public void BlanketStartDateTest()
        {
            // TODO unit test for the property 'BlanketStartDate'
        }
        /// <summary>
        /// Test the property 'CertificateNumber'
        /// </summary>
        [Test]
        public void CertificateNumberTest()
        {
            // TODO unit test for the property 'CertificateNumber'
        }
        /// <summary>
        /// Test the property 'Comments'
        /// </summary>
        [Test]
        public void CommentsTest()
        {
            // TODO unit test for the property 'Comments'
        }
        /// <summary>
        /// Test the property 'CurrencyCode'
        /// </summary>
        [Test]
        public void CurrencyCodeTest()
        {
            // TODO unit test for the property 'CurrencyCode'
        }
        /// <summary>
        /// Test the property 'CustomsDeclaredValue'
        /// </summary>
        [Test]
        public void CustomsDeclaredValueTest()
        {
            // TODO unit test for the property 'CustomsDeclaredValue'
        }
        /// <summary>
        /// Test the property 'DeclarationStatement'
        /// </summary>
        [Test]
        public void DeclarationStatementTest()
        {
            // TODO unit test for the property 'DeclarationStatement'
        }
        /// <summary>
        /// Test the property 'FreightCharge'
        /// </summary>
        [Test]
        public void FreightChargeTest()
        {
            // TODO unit test for the property 'FreightCharge'
        }
        /// <summary>
        /// Test the property 'FromCustomsReference'
        /// </summary>
        [Test]
        public void FromCustomsReferenceTest()
        {
            // TODO unit test for the property 'FromCustomsReference'
        }
        /// <summary>
        /// Test the property 'HandlingCosts'
        /// </summary>
        [Test]
        public void HandlingCostsTest()
        {
            // TODO unit test for the property 'HandlingCosts'
        }
        /// <summary>
        /// Test the property 'ImporterCustomsReference'
        /// </summary>
        [Test]
        public void ImporterCustomsReferenceTest()
        {
            // TODO unit test for the property 'ImporterCustomsReference'
        }
        /// <summary>
        /// Test the property 'InsuredAmount'
        /// </summary>
        [Test]
        public void InsuredAmountTest()
        {
            // TODO unit test for the property 'InsuredAmount'
        }
        /// <summary>
        /// Test the property 'InsuredNumber'
        /// </summary>
        [Test]
        public void InsuredNumberTest()
        {
            // TODO unit test for the property 'InsuredNumber'
        }
        /// <summary>
        /// Test the property 'InvoiceNumber'
        /// </summary>
        [Test]
        public void InvoiceNumberTest()
        {
            // TODO unit test for the property 'InvoiceNumber'
        }
        /// <summary>
        /// Test the property 'LicenseNumber'
        /// </summary>
        [Test]
        public void LicenseNumberTest()
        {
            // TODO unit test for the property 'LicenseNumber'
        }
        /// <summary>
        /// Test the property 'OtherCharge'
        /// </summary>
        [Test]
        public void OtherChargeTest()
        {
            // TODO unit test for the property 'OtherCharge'
        }
        /// <summary>
        /// Test the property 'OtherDescription'
        /// </summary>
        [Test]
        public void OtherDescriptionTest()
        {
            // TODO unit test for the property 'OtherDescription'
        }
        /// <summary>
        /// Test the property 'OtherType'
        /// </summary>
        [Test]
        public void OtherTypeTest()
        {
            // TODO unit test for the property 'OtherType'
        }
        /// <summary>
        /// Test the property 'PackingCosts'
        /// </summary>
        [Test]
        public void PackingCostsTest()
        {
            // TODO unit test for the property 'PackingCosts'
        }
        /// <summary>
        /// Test the property 'ProducerSpecification'
        /// </summary>
        [Test]
        public void ProducerSpecificationTest()
        {
            // TODO unit test for the property 'ProducerSpecification'
        }
        /// <summary>
        /// Test the property 'ReasonForExport'
        /// </summary>
        [Test]
        public void ReasonForExportTest()
        {
            // TODO unit test for the property 'ReasonForExport'
        }
        /// <summary>
        /// Test the property 'ReasonForExportExplanation'
        /// </summary>
        [Test]
        public void ReasonForExportExplanationTest()
        {
            // TODO unit test for the property 'ReasonForExportExplanation'
        }
        /// <summary>
        /// Test the property 'SdrValue'
        /// </summary>
        [Test]
        public void SdrValueTest()
        {
            // TODO unit test for the property 'SdrValue'
        }
        /// <summary>
        /// Test the property 'ShippingDocumentType'
        /// </summary>
        [Test]
        public void ShippingDocumentTypeTest()
        {
            // TODO unit test for the property 'ShippingDocumentType'
        }
        /// <summary>
        /// Test the property 'SignatureContact'
        /// </summary>
        [Test]
        public void SignatureContactTest()
        {
            // TODO unit test for the property 'SignatureContact'
        }
        /// <summary>
        /// Test the property 'TermsOfSale'
        /// </summary>
        [Test]
        public void TermsOfSaleTest()
        {
            // TODO unit test for the property 'TermsOfSale'
        }

    }

}
