/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing DeliveryCommitment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DeliveryCommitmentTests
    {
        // TODO uncomment below to declare an instance variable for DeliveryCommitment
        //private DeliveryCommitment instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DeliveryCommitment
            //instance = new DeliveryCommitment();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DeliveryCommitment
        /// </summary>
        [Test]
        public void DeliveryCommitmentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" DeliveryCommitment
            //Assert.IsInstanceOf(typeof(DeliveryCommitment), instance);
        }


        /// <summary>
        /// Test the property 'AdditionalDetails'
        /// </summary>
        [Test]
        public void AdditionalDetailsTest()
        {
            // TODO unit test for the property 'AdditionalDetails'
        }
        /// <summary>
        /// Test the property 'EstimatedDeliveryDateTime'
        /// </summary>
        [Test]
        public void EstimatedDeliveryDateTimeTest()
        {
            // TODO unit test for the property 'EstimatedDeliveryDateTime'
        }
        /// <summary>
        /// Test the property 'Guarantee'
        /// </summary>
        [Test]
        public void GuaranteeTest()
        {
            // TODO unit test for the property 'Guarantee'
        }
        /// <summary>
        /// Test the property 'MaxEstimatedNumberOfDays'
        /// </summary>
        [Test]
        public void MaxEstimatedNumberOfDaysTest()
        {
            // TODO unit test for the property 'MaxEstimatedNumberOfDays'
        }
        /// <summary>
        /// Test the property 'MinEstimatedNumberOfDays'
        /// </summary>
        [Test]
        public void MinEstimatedNumberOfDaysTest()
        {
            // TODO unit test for the property 'MinEstimatedNumberOfDays'
        }

    }

}
