/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing DimensionRulesMaxParcelDimensions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DimensionRulesMaxParcelDimensionsTests
    {
        // TODO uncomment below to declare an instance variable for DimensionRulesMaxParcelDimensions
        //private DimensionRulesMaxParcelDimensions instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DimensionRulesMaxParcelDimensions
            //instance = new DimensionRulesMaxParcelDimensions();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DimensionRulesMaxParcelDimensions
        /// </summary>
        [Test]
        public void DimensionRulesMaxParcelDimensionsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" DimensionRulesMaxParcelDimensions
            //Assert.IsInstanceOf(typeof(DimensionRulesMaxParcelDimensions), instance);
        }


        /// <summary>
        /// Test the property 'Length'
        /// </summary>
        [Test]
        public void LengthTest()
        {
            // TODO unit test for the property 'Length'
        }
        /// <summary>
        /// Test the property 'Width'
        /// </summary>
        [Test]
        public void WidthTest()
        {
            // TODO unit test for the property 'Width'
        }
        /// <summary>
        /// Test the property 'Height'
        /// </summary>
        [Test]
        public void HeightTest()
        {
            // TODO unit test for the property 'Height'
        }
        /// <summary>
        /// Test the property 'UnitOfMeasurement'
        /// </summary>
        [Test]
        public void UnitOfMeasurementTest()
        {
            // TODO unit test for the property 'UnitOfMeasurement'
        }

    }

}
