/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing DimensionRules
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DimensionRulesTests
    {
        // TODO uncomment below to declare an instance variable for DimensionRules
        //private DimensionRules instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DimensionRules
            //instance = new DimensionRules();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DimensionRules
        /// </summary>
        [Test]
        public void DimensionRulesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" DimensionRules
            //Assert.IsInstanceOf(typeof(DimensionRules), instance);
        }


        /// <summary>
        /// Test the property 'Required'
        /// </summary>
        [Test]
        public void RequiredTest()
        {
            // TODO unit test for the property 'Required'
        }
        /// <summary>
        /// Test the property 'UnitOfMeasurement'
        /// </summary>
        [Test]
        public void UnitOfMeasurementTest()
        {
            // TODO unit test for the property 'UnitOfMeasurement'
        }
        /// <summary>
        /// Test the property 'MinParcelDimensions'
        /// </summary>
        [Test]
        public void MinParcelDimensionsTest()
        {
            // TODO unit test for the property 'MinParcelDimensions'
        }
        /// <summary>
        /// Test the property 'MaxParcelDimensions'
        /// </summary>
        [Test]
        public void MaxParcelDimensionsTest()
        {
            // TODO unit test for the property 'MaxParcelDimensions'
        }
        /// <summary>
        /// Test the property 'MinLengthPlusGirth'
        /// </summary>
        [Test]
        public void MinLengthPlusGirthTest()
        {
            // TODO unit test for the property 'MinLengthPlusGirth'
        }
        /// <summary>
        /// Test the property 'MaxLengthPlusGirth'
        /// </summary>
        [Test]
        public void MaxLengthPlusGirthTest()
        {
            // TODO unit test for the property 'MaxLengthPlusGirth'
        }

    }

}
