/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing DocumentPage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DocumentPageTests
    {
        // TODO uncomment below to declare an instance variable for DocumentPage
        //private DocumentPage instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DocumentPage
            //instance = new DocumentPage();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DocumentPage
        /// </summary>
        [Test]
        public void DocumentPageInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" DocumentPage
            //Assert.IsInstanceOf(typeof(DocumentPage), instance);
        }


        /// <summary>
        /// Test the property 'Contents'
        /// </summary>
        [Test]
        public void ContentsTest()
        {
            // TODO unit test for the property 'Contents'
        }

    }

}
