/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing Document
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DocumentTests
    {
        // TODO uncomment below to declare an instance variable for Document
        //private Document instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Document
            //instance = new Document();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Document
        /// </summary>
        [Test]
        public void DocumentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" Document
            //Assert.IsInstanceOf(typeof(Document), instance);
        }


        /// <summary>
        /// Test the property 'ContentType'
        /// </summary>
        [Test]
        public void ContentTypeTest()
        {
            // TODO unit test for the property 'ContentType'
        }
        /// <summary>
        /// Test the property 'Contents'
        /// </summary>
        [Test]
        public void ContentsTest()
        {
            // TODO unit test for the property 'Contents'
        }
        /// <summary>
        /// Test the property 'DocTab'
        /// </summary>
        [Test]
        public void DocTabTest()
        {
            // TODO unit test for the property 'DocTab'
        }
        /// <summary>
        /// Test the property 'FileFormat'
        /// </summary>
        [Test]
        public void FileFormatTest()
        {
            // TODO unit test for the property 'FileFormat'
        }
        /// <summary>
        /// Test the property 'Pages'
        /// </summary>
        [Test]
        public void PagesTest()
        {
            // TODO unit test for the property 'Pages'
        }
        /// <summary>
        /// Test the property 'PrintDialogOption'
        /// </summary>
        [Test]
        public void PrintDialogOptionTest()
        {
            // TODO unit test for the property 'PrintDialogOption'
        }
        /// <summary>
        /// Test the property 'Resolution'
        /// </summary>
        [Test]
        public void ResolutionTest()
        {
            // TODO unit test for the property 'Resolution'
        }
        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Test]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
