/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing HazmatDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HazmatDetailsTests
    {
        // TODO uncomment below to declare an instance variable for HazmatDetails
        //private HazmatDetails instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of HazmatDetails
            //instance = new HazmatDetails();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of HazmatDetails
        /// </summary>
        [Test]
        public void HazmatDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" HazmatDetails
            //Assert.IsInstanceOf(typeof(HazmatDetails), instance);
        }


        /// <summary>
        /// Test the property 'BatteryDetails'
        /// </summary>
        [Test]
        public void BatteryDetailsTest()
        {
            // TODO unit test for the property 'BatteryDetails'
        }
        /// <summary>
        /// Test the property 'CommodityType'
        /// </summary>
        [Test]
        public void CommodityTypeTest()
        {
            // TODO unit test for the property 'CommodityType'
        }
        /// <summary>
        /// Test the property 'ContainerCount'
        /// </summary>
        [Test]
        public void ContainerCountTest()
        {
            // TODO unit test for the property 'ContainerCount'
        }
        /// <summary>
        /// Test the property 'ContainerDetails'
        /// </summary>
        [Test]
        public void ContainerDetailsTest()
        {
            // TODO unit test for the property 'ContainerDetails'
        }
        /// <summary>
        /// Test the property 'EmergencyContactNumber'
        /// </summary>
        [Test]
        public void EmergencyContactNumberTest()
        {
            // TODO unit test for the property 'EmergencyContactNumber'
        }
        /// <summary>
        /// Test the property 'HazmatDocumentType'
        /// </summary>
        [Test]
        public void HazmatDocumentTypeTest()
        {
            // TODO unit test for the property 'HazmatDocumentType'
        }
        /// <summary>
        /// Test the property 'IdenticalContainers'
        /// </summary>
        [Test]
        public void IdenticalContainersTest()
        {
            // TODO unit test for the property 'IdenticalContainers'
        }
        /// <summary>
        /// Test the property 'Offeror'
        /// </summary>
        [Test]
        public void OfferorTest()
        {
            // TODO unit test for the property 'Offeror'
        }
        /// <summary>
        /// Test the property 'PackagingOption'
        /// </summary>
        [Test]
        public void PackagingOptionTest()
        {
            // TODO unit test for the property 'PackagingOption'
        }
        /// <summary>
        /// Test the property 'Signatory'
        /// </summary>
        [Test]
        public void SignatoryTest()
        {
            // TODO unit test for the property 'Signatory'
        }

    }

}
