/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing InfectiousSubstanceContact
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InfectiousSubstanceContactTests
    {
        // TODO uncomment below to declare an instance variable for InfectiousSubstanceContact
        //private InfectiousSubstanceContact instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InfectiousSubstanceContact
            //instance = new InfectiousSubstanceContact();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InfectiousSubstanceContact
        /// </summary>
        [Test]
        public void InfectiousSubstanceContactInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" InfectiousSubstanceContact
            //Assert.IsInstanceOf(typeof(InfectiousSubstanceContact), instance);
        }


        /// <summary>
        /// Test the property 'CompanyName'
        /// </summary>
        [Test]
        public void CompanyNameTest()
        {
            // TODO unit test for the property 'CompanyName'
        }
        /// <summary>
        /// Test the property 'ContactId'
        /// </summary>
        [Test]
        public void ContactIdTest()
        {
            // TODO unit test for the property 'ContactId'
        }
        /// <summary>
        /// Test the property 'EmailAddress'
        /// </summary>
        [Test]
        public void EmailAddressTest()
        {
            // TODO unit test for the property 'EmailAddress'
        }
        /// <summary>
        /// Test the property 'PersonName'
        /// </summary>
        [Test]
        public void PersonNameTest()
        {
            // TODO unit test for the property 'PersonName'
        }
        /// <summary>
        /// Test the property 'PhoneNumber'
        /// </summary>
        [Test]
        public void PhoneNumberTest()
        {
            // TODO unit test for the property 'PhoneNumber'
        }

    }

}
