/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing Manifest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ManifestTests
    {
        // TODO uncomment below to declare an instance variable for Manifest
        //private Manifest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Manifest
            //instance = new Manifest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Manifest
        /// </summary>
        [Test]
        public void ManifestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" Manifest
            //Assert.IsInstanceOf(typeof(Manifest), instance);
        }


        /// <summary>
        /// Test the property 'Carrier'
        /// </summary>
        [Test]
        public void CarrierTest()
        {
            // TODO unit test for the property 'Carrier'
        }
        /// <summary>
        /// Test the property 'Documents'
        /// </summary>
        [Test]
        public void DocumentsTest()
        {
            // TODO unit test for the property 'Documents'
        }
        /// <summary>
        /// Test the property 'FromAddress'
        /// </summary>
        [Test]
        public void FromAddressTest()
        {
            // TODO unit test for the property 'FromAddress'
        }
        /// <summary>
        /// Test the property 'InductionPostalCode'
        /// </summary>
        [Test]
        public void InductionPostalCodeTest()
        {
            // TODO unit test for the property 'InductionPostalCode'
        }
        /// <summary>
        /// Test the property 'ManifestId'
        /// </summary>
        [Test]
        public void ManifestIdTest()
        {
            // TODO unit test for the property 'ManifestId'
        }
        /// <summary>
        /// Test the property 'ManifestTrackingNumber'
        /// </summary>
        [Test]
        public void ManifestTrackingNumberTest()
        {
            // TODO unit test for the property 'ManifestTrackingNumber'
        }
        /// <summary>
        /// Test the property 'Parameters'
        /// </summary>
        [Test]
        public void ParametersTest()
        {
            // TODO unit test for the property 'Parameters'
        }
        /// <summary>
        /// Test the property 'ParcelTrackingNumbers'
        /// </summary>
        [Test]
        public void ParcelTrackingNumbersTest()
        {
            // TODO unit test for the property 'ParcelTrackingNumbers'
        }
        /// <summary>
        /// Test the property 'SubmissionDate'
        /// </summary>
        [Test]
        public void SubmissionDateTest()
        {
            // TODO unit test for the property 'SubmissionDate'
        }

    }

}
