/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing ParcelProtectionCreateResponseParcelProtectionFeesBreakup
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ParcelProtectionCreateResponseParcelProtectionFeesBreakupTests
    {
        // TODO uncomment below to declare an instance variable for ParcelProtectionCreateResponseParcelProtectionFeesBreakup
        //private ParcelProtectionCreateResponseParcelProtectionFeesBreakup instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ParcelProtectionCreateResponseParcelProtectionFeesBreakup
            //instance = new ParcelProtectionCreateResponseParcelProtectionFeesBreakup();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ParcelProtectionCreateResponseParcelProtectionFeesBreakup
        /// </summary>
        [Test]
        public void ParcelProtectionCreateResponseParcelProtectionFeesBreakupInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ParcelProtectionCreateResponseParcelProtectionFeesBreakup
            //Assert.IsInstanceOf(typeof(ParcelProtectionCreateResponseParcelProtectionFeesBreakup), instance);
        }


        /// <summary>
        /// Test the property 'BasePremium'
        /// </summary>
        [Test]
        public void BasePremiumTest()
        {
            // TODO unit test for the property 'BasePremium'
        }
        /// <summary>
        /// Test the property 'TechnologyFee'
        /// </summary>
        [Test]
        public void TechnologyFeeTest()
        {
            // TODO unit test for the property 'TechnologyFee'
        }

    }

}
