/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing Parcel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ParcelTests
    {
        // TODO uncomment below to declare an instance variable for Parcel
        //private Parcel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Parcel
            //instance = new Parcel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Parcel
        /// </summary>
        [Test]
        public void ParcelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" Parcel
            //Assert.IsInstanceOf(typeof(Parcel), instance);
        }


        /// <summary>
        /// Test the property 'Dimension'
        /// </summary>
        [Test]
        public void DimensionTest()
        {
            // TODO unit test for the property 'Dimension'
        }
        /// <summary>
        /// Test the property 'Weight'
        /// </summary>
        [Test]
        public void WeightTest()
        {
            // TODO unit test for the property 'Weight'
        }
        /// <summary>
        /// Test the property 'ValueOfGoods'
        /// </summary>
        [Test]
        public void ValueOfGoodsTest()
        {
            // TODO unit test for the property 'ValueOfGoods'
        }
        /// <summary>
        /// Test the property 'CurrencyCode'
        /// </summary>
        [Test]
        public void CurrencyCodeTest()
        {
            // TODO unit test for the property 'CurrencyCode'
        }

    }

}
