/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing ParcelProtectionPolicyResponseShipperInfoAddress
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ParcelProtectionPolicyResponseShipperInfoAddressTests
    {
        // TODO uncomment below to declare an instance variable for ParcelProtectionPolicyResponseShipperInfoAddress
        //private ParcelProtectionPolicyResponseShipperInfoAddress instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ParcelProtectionPolicyResponseShipperInfoAddress
            //instance = new ParcelProtectionPolicyResponseShipperInfoAddress();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ParcelProtectionPolicyResponseShipperInfoAddress
        /// </summary>
        [Test]
        public void ParcelProtectionPolicyResponseShipperInfoAddressInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ParcelProtectionPolicyResponseShipperInfoAddress
            //Assert.IsInstanceOf(typeof(ParcelProtectionPolicyResponseShipperInfoAddress), instance);
        }


        /// <summary>
        /// Test the property 'Street1'
        /// </summary>
        [Test]
        public void Street1Test()
        {
            // TODO unit test for the property 'Street1'
        }
        /// <summary>
        /// Test the property 'Street2'
        /// </summary>
        [Test]
        public void Street2Test()
        {
            // TODO unit test for the property 'Street2'
        }
        /// <summary>
        /// Test the property 'Street3'
        /// </summary>
        [Test]
        public void Street3Test()
        {
            // TODO unit test for the property 'Street3'
        }
        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Test]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }
        /// <summary>
        /// Test the property 'Region'
        /// </summary>
        [Test]
        public void RegionTest()
        {
            // TODO unit test for the property 'Region'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Test]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }
        /// <summary>
        /// Test the property 'PostalCode'
        /// </summary>
        [Test]
        public void PostalCodeTest()
        {
            // TODO unit test for the property 'PostalCode'
        }

    }

}
