/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing ParcelWeight
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ParcelWeightTests
    {
        // TODO uncomment below to declare an instance variable for ParcelWeight
        //private ParcelWeight instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ParcelWeight
            //instance = new ParcelWeight();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ParcelWeight
        /// </summary>
        [Test]
        public void ParcelWeightInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ParcelWeight
            //Assert.IsInstanceOf(typeof(ParcelWeight), instance);
        }


        /// <summary>
        /// Test the property 'Weight'
        /// </summary>
        [Test]
        public void WeightTest()
        {
            // TODO unit test for the property 'Weight'
        }
        /// <summary>
        /// Test the property 'UnitOfMeasurement'
        /// </summary>
        [Test]
        public void UnitOfMeasurementTest()
        {
            // TODO unit test for the property 'UnitOfMeasurement'
        }

    }

}
