/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing ParcelProtectionQuoteResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ParcelProtectionQuoteResponseTests
    {
        // TODO uncomment below to declare an instance variable for ParcelProtectionQuoteResponse
        //private ParcelProtectionQuoteResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ParcelProtectionQuoteResponse
            //instance = new ParcelProtectionQuoteResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ParcelProtectionQuoteResponse
        /// </summary>
        [Test]
        public void ParcelProtectionQuoteResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ParcelProtectionQuoteResponse
            //Assert.IsInstanceOf(typeof(ParcelProtectionQuoteResponse), instance);
        }


        /// <summary>
        /// Test the property 'ParcelProtectionFees'
        /// </summary>
        [Test]
        public void ParcelProtectionFeesTest()
        {
            // TODO unit test for the property 'ParcelProtectionFees'
        }
        /// <summary>
        /// Test the property 'ParcelProtectionFeesCurrencyCode'
        /// </summary>
        [Test]
        public void ParcelProtectionFeesCurrencyCodeTest()
        {
            // TODO unit test for the property 'ParcelProtectionFeesCurrencyCode'
        }
        /// <summary>
        /// Test the property 'ParcelProtectionFeesBreakup'
        /// </summary>
        [Test]
        public void ParcelProtectionFeesBreakupTest()
        {
            // TODO unit test for the property 'ParcelProtectionFeesBreakup'
        }

    }

}
