/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing ParcelProtectionPolicyResponseContent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ParcelProtectionPolicyResponseContentTests
    {
        // TODO uncomment below to declare an instance variable for ParcelProtectionPolicyResponseContent
        //private ParcelProtectionPolicyResponseContent instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ParcelProtectionPolicyResponseContent
            //instance = new ParcelProtectionPolicyResponseContent();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ParcelProtectionPolicyResponseContent
        /// </summary>
        [Test]
        public void ParcelProtectionPolicyResponseContentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ParcelProtectionPolicyResponseContent
            //Assert.IsInstanceOf(typeof(ParcelProtectionPolicyResponseContent), instance);
        }


        /// <summary>
        /// Test the property 'TransactionId'
        /// </summary>
        [Test]
        public void TransactionIdTest()
        {
            // TODO unit test for the property 'TransactionId'
        }
        /// <summary>
        /// Test the property 'DeveloperId'
        /// </summary>
        [Test]
        public void DeveloperIdTest()
        {
            // TODO unit test for the property 'DeveloperId'
        }
        /// <summary>
        /// Test the property 'SubscriptionAccNo'
        /// </summary>
        [Test]
        public void SubscriptionAccNoTest()
        {
            // TODO unit test for the property 'SubscriptionAccNo'
        }
        /// <summary>
        /// Test the property 'ClientTransactionId'
        /// </summary>
        [Test]
        public void ClientTransactionIdTest()
        {
            // TODO unit test for the property 'ClientTransactionId'
        }
        /// <summary>
        /// Test the property 'PolicyDetails'
        /// </summary>
        [Test]
        public void PolicyDetailsTest()
        {
            // TODO unit test for the property 'PolicyDetails'
        }
        /// <summary>
        /// Test the property 'ShipmentDetails'
        /// </summary>
        [Test]
        public void ShipmentDetailsTest()
        {
            // TODO unit test for the property 'ShipmentDetails'
        }
        /// <summary>
        /// Test the property 'ShipperInfo'
        /// </summary>
        [Test]
        public void ShipperInfoTest()
        {
            // TODO unit test for the property 'ShipperInfo'
        }
        /// <summary>
        /// Test the property 'ConsigneeInfo'
        /// </summary>
        [Test]
        public void ConsigneeInfoTest()
        {
            // TODO unit test for the property 'ConsigneeInfo'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Test]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

    }

}
