/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing ParcelProtectionPolicyResponseSort
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ParcelProtectionPolicyResponseSortTests
    {
        // TODO uncomment below to declare an instance variable for ParcelProtectionPolicyResponseSort
        //private ParcelProtectionPolicyResponseSort instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ParcelProtectionPolicyResponseSort
            //instance = new ParcelProtectionPolicyResponseSort();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ParcelProtectionPolicyResponseSort
        /// </summary>
        [Test]
        public void ParcelProtectionPolicyResponseSortInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ParcelProtectionPolicyResponseSort
            //Assert.IsInstanceOf(typeof(ParcelProtectionPolicyResponseSort), instance);
        }


        /// <summary>
        /// Test the property 'Direction'
        /// </summary>
        [Test]
        public void DirectionTest()
        {
            // TODO unit test for the property 'Direction'
        }
        /// <summary>
        /// Test the property 'Property'
        /// </summary>
        [Test]
        public void PropertyTest()
        {
            // TODO unit test for the property 'Property'
        }
        /// <summary>
        /// Test the property 'IgnoreCase'
        /// </summary>
        [Test]
        public void IgnoreCaseTest()
        {
            // TODO unit test for the property 'IgnoreCase'
        }
        /// <summary>
        /// Test the property 'NullHandling'
        /// </summary>
        [Test]
        public void NullHandlingTest()
        {
            // TODO unit test for the property 'NullHandling'
        }
        /// <summary>
        /// Test the property 'Descending'
        /// </summary>
        [Test]
        public void DescendingTest()
        {
            // TODO unit test for the property 'Descending'
        }
        /// <summary>
        /// Test the property 'Ascending'
        /// </summary>
        [Test]
        public void AscendingTest()
        {
            // TODO unit test for the property 'Ascending'
        }

    }

}
