/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing ParcelProtectionPolicyResponseShipmentDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ParcelProtectionPolicyResponseShipmentDetailsTests
    {
        // TODO uncomment below to declare an instance variable for ParcelProtectionPolicyResponseShipmentDetails
        //private ParcelProtectionPolicyResponseShipmentDetails instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ParcelProtectionPolicyResponseShipmentDetails
            //instance = new ParcelProtectionPolicyResponseShipmentDetails();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ParcelProtectionPolicyResponseShipmentDetails
        /// </summary>
        [Test]
        public void ParcelProtectionPolicyResponseShipmentDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ParcelProtectionPolicyResponseShipmentDetails
            //Assert.IsInstanceOf(typeof(ParcelProtectionPolicyResponseShipmentDetails), instance);
        }


        /// <summary>
        /// Test the property 'ShipmentDate'
        /// </summary>
        [Test]
        public void ShipmentDateTest()
        {
            // TODO unit test for the property 'ShipmentDate'
        }
        /// <summary>
        /// Test the property 'ShipmentTransactionId'
        /// </summary>
        [Test]
        public void ShipmentTransactionIdTest()
        {
            // TODO unit test for the property 'ShipmentTransactionId'
        }
        /// <summary>
        /// Test the property 'ShipmentId'
        /// </summary>
        [Test]
        public void ShipmentIdTest()
        {
            // TODO unit test for the property 'ShipmentId'
        }
        /// <summary>
        /// Test the property 'ParcelTrackingNumber'
        /// </summary>
        [Test]
        public void ParcelTrackingNumberTest()
        {
            // TODO unit test for the property 'ParcelTrackingNumber'
        }
        /// <summary>
        /// Test the property 'Carrier'
        /// </summary>
        [Test]
        public void CarrierTest()
        {
            // TODO unit test for the property 'Carrier'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Test]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'PackageLength'
        /// </summary>
        [Test]
        public void PackageLengthTest()
        {
            // TODO unit test for the property 'PackageLength'
        }
        /// <summary>
        /// Test the property 'PackageWidth'
        /// </summary>
        [Test]
        public void PackageWidthTest()
        {
            // TODO unit test for the property 'PackageWidth'
        }
        /// <summary>
        /// Test the property 'PackageHeight'
        /// </summary>
        [Test]
        public void PackageHeightTest()
        {
            // TODO unit test for the property 'PackageHeight'
        }
        /// <summary>
        /// Test the property 'Weight'
        /// </summary>
        [Test]
        public void WeightTest()
        {
            // TODO unit test for the property 'Weight'
        }
        /// <summary>
        /// Test the property 'Zone'
        /// </summary>
        [Test]
        public void ZoneTest()
        {
            // TODO unit test for the property 'Zone'
        }

    }

}
