/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing ParcelProtectionPolicyResponsePolicyDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ParcelProtectionPolicyResponsePolicyDetailsTests
    {
        // TODO uncomment below to declare an instance variable for ParcelProtectionPolicyResponsePolicyDetails
        //private ParcelProtectionPolicyResponsePolicyDetails instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ParcelProtectionPolicyResponsePolicyDetails
            //instance = new ParcelProtectionPolicyResponsePolicyDetails();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ParcelProtectionPolicyResponsePolicyDetails
        /// </summary>
        [Test]
        public void ParcelProtectionPolicyResponsePolicyDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ParcelProtectionPolicyResponsePolicyDetails
            //Assert.IsInstanceOf(typeof(ParcelProtectionPolicyResponsePolicyDetails), instance);
        }


        /// <summary>
        /// Test the property 'PolicyId'
        /// </summary>
        [Test]
        public void PolicyIdTest()
        {
            // TODO unit test for the property 'PolicyId'
        }
        /// <summary>
        /// Test the property 'PolicyDate'
        /// </summary>
        [Test]
        public void PolicyDateTest()
        {
            // TODO unit test for the property 'PolicyDate'
        }
        /// <summary>
        /// Test the property 'PolicyStatus'
        /// </summary>
        [Test]
        public void PolicyStatusTest()
        {
            // TODO unit test for the property 'PolicyStatus'
        }
        /// <summary>
        /// Test the property 'ClaimStatus'
        /// </summary>
        [Test]
        public void ClaimStatusTest()
        {
            // TODO unit test for the property 'ClaimStatus'
        }
        /// <summary>
        /// Test the property 'ClaimStatusUpdateDate'
        /// </summary>
        [Test]
        public void ClaimStatusUpdateDateTest()
        {
            // TODO unit test for the property 'ClaimStatusUpdateDate'
        }
        /// <summary>
        /// Test the property 'ValueOfGoods'
        /// </summary>
        [Test]
        public void ValueOfGoodsTest()
        {
            // TODO unit test for the property 'ValueOfGoods'
        }
        /// <summary>
        /// Test the property 'InsuranceValue'
        /// </summary>
        [Test]
        public void InsuranceValueTest()
        {
            // TODO unit test for the property 'InsuranceValue'
        }
        /// <summary>
        /// Test the property 'PremiumValue'
        /// </summary>
        [Test]
        public void PremiumValueTest()
        {
            // TODO unit test for the property 'PremiumValue'
        }
        /// <summary>
        /// Test the property 'BasePremium'
        /// </summary>
        [Test]
        public void BasePremiumTest()
        {
            // TODO unit test for the property 'BasePremium'
        }
        /// <summary>
        /// Test the property 'TechnologyFee'
        /// </summary>
        [Test]
        public void TechnologyFeeTest()
        {
            // TODO unit test for the property 'TechnologyFee'
        }
        /// <summary>
        /// Test the property 'CurrencyCode'
        /// </summary>
        [Test]
        public void CurrencyCodeTest()
        {
            // TODO unit test for the property 'CurrencyCode'
        }
        /// <summary>
        /// Test the property 'MailClass'
        /// </summary>
        [Test]
        public void MailClassTest()
        {
            // TODO unit test for the property 'MailClass'
        }
        /// <summary>
        /// Test the property 'MailClassOption'
        /// </summary>
        [Test]
        public void MailClassOptionTest()
        {
            // TODO unit test for the property 'MailClassOption'
        }

    }

}
