/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing ParcelTypeRules
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ParcelTypeRulesTests
    {
        // TODO uncomment below to declare an instance variable for ParcelTypeRules
        //private ParcelTypeRules instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ParcelTypeRules
            //instance = new ParcelTypeRules();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ParcelTypeRules
        /// </summary>
        [Test]
        public void ParcelTypeRulesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ParcelTypeRules
            //Assert.IsInstanceOf(typeof(ParcelTypeRules), instance);
        }


        /// <summary>
        /// Test the property 'ParcelType'
        /// </summary>
        [Test]
        public void ParcelTypeTest()
        {
            // TODO unit test for the property 'ParcelType'
        }
        /// <summary>
        /// Test the property 'BrandedName'
        /// </summary>
        [Test]
        public void BrandedNameTest()
        {
            // TODO unit test for the property 'BrandedName'
        }
        /// <summary>
        /// Test the property 'RateTypeId'
        /// </summary>
        [Test]
        public void RateTypeIdTest()
        {
            // TODO unit test for the property 'RateTypeId'
        }
        /// <summary>
        /// Test the property 'RateTypeBrandedName'
        /// </summary>
        [Test]
        public void RateTypeBrandedNameTest()
        {
            // TODO unit test for the property 'RateTypeBrandedName'
        }
        /// <summary>
        /// Test the property 'Trackable'
        /// </summary>
        [Test]
        public void TrackableTest()
        {
            // TODO unit test for the property 'Trackable'
        }
        /// <summary>
        /// Test the property 'SpecialServicesRule'
        /// </summary>
        [Test]
        public void SpecialServicesRuleTest()
        {
            // TODO unit test for the property 'SpecialServicesRule'
        }
        /// <summary>
        /// Test the property 'WeightRules'
        /// </summary>
        [Test]
        public void WeightRulesTest()
        {
            // TODO unit test for the property 'WeightRules'
        }
        /// <summary>
        /// Test the property 'DimensionRules'
        /// </summary>
        [Test]
        public void DimensionRulesTest()
        {
            // TODO unit test for the property 'DimensionRules'
        }
        /// <summary>
        /// Test the property 'SuggestedTrackableSpecialServiceId'
        /// </summary>
        [Test]
        public void SuggestedTrackableSpecialServiceIdTest()
        {
            // TODO unit test for the property 'SuggestedTrackableSpecialServiceId'
        }

    }

}
