/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing ParcelProtectionQuoteRequestShipmentInfoParcelInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ParcelProtectionQuoteRequestShipmentInfoParcelInfoTests
    {
        // TODO uncomment below to declare an instance variable for ParcelProtectionQuoteRequestShipmentInfoParcelInfo
        //private ParcelProtectionQuoteRequestShipmentInfoParcelInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ParcelProtectionQuoteRequestShipmentInfoParcelInfo
            //instance = new ParcelProtectionQuoteRequestShipmentInfoParcelInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ParcelProtectionQuoteRequestShipmentInfoParcelInfo
        /// </summary>
        [Test]
        public void ParcelProtectionQuoteRequestShipmentInfoParcelInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ParcelProtectionQuoteRequestShipmentInfoParcelInfo
            //Assert.IsInstanceOf(typeof(ParcelProtectionQuoteRequestShipmentInfoParcelInfo), instance);
        }


        /// <summary>
        /// Test the property 'CommodityList'
        /// </summary>
        [Test]
        public void CommodityListTest()
        {
            // TODO unit test for the property 'CommodityList'
        }

    }

}
