/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing ParcelProtectionQuoteRequestShipmentInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ParcelProtectionQuoteRequestShipmentInfoTests
    {
        // TODO uncomment below to declare an instance variable for ParcelProtectionQuoteRequestShipmentInfo
        //private ParcelProtectionQuoteRequestShipmentInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ParcelProtectionQuoteRequestShipmentInfo
            //instance = new ParcelProtectionQuoteRequestShipmentInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ParcelProtectionQuoteRequestShipmentInfo
        /// </summary>
        [Test]
        public void ParcelProtectionQuoteRequestShipmentInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ParcelProtectionQuoteRequestShipmentInfo
            //Assert.IsInstanceOf(typeof(ParcelProtectionQuoteRequestShipmentInfo), instance);
        }


        /// <summary>
        /// Test the property 'Carrier'
        /// </summary>
        [Test]
        public void CarrierTest()
        {
            // TODO unit test for the property 'Carrier'
        }
        /// <summary>
        /// Test the property 'ServiceId'
        /// </summary>
        [Test]
        public void ServiceIdTest()
        {
            // TODO unit test for the property 'ServiceId'
        }
        /// <summary>
        /// Test the property 'InsuranceCoverageValue'
        /// </summary>
        [Test]
        public void InsuranceCoverageValueTest()
        {
            // TODO unit test for the property 'InsuranceCoverageValue'
        }
        /// <summary>
        /// Test the property 'InsuranceCoverageValueCurrency'
        /// </summary>
        [Test]
        public void InsuranceCoverageValueCurrencyTest()
        {
            // TODO unit test for the property 'InsuranceCoverageValueCurrency'
        }
        /// <summary>
        /// Test the property 'ParcelInfo'
        /// </summary>
        [Test]
        public void ParcelInfoTest()
        {
            // TODO unit test for the property 'ParcelInfo'
        }
        /// <summary>
        /// Test the property 'ShipperInfo'
        /// </summary>
        [Test]
        public void ShipperInfoTest()
        {
            // TODO unit test for the property 'ShipperInfo'
        }
        /// <summary>
        /// Test the property 'ConsigneeInfo'
        /// </summary>
        [Test]
        public void ConsigneeInfoTest()
        {
            // TODO unit test for the property 'ConsigneeInfo'
        }

    }

}
