/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing ParcelProtectionPolicyResponseShipperInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ParcelProtectionPolicyResponseShipperInfoTests
    {
        // TODO uncomment below to declare an instance variable for ParcelProtectionPolicyResponseShipperInfo
        //private ParcelProtectionPolicyResponseShipperInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ParcelProtectionPolicyResponseShipperInfo
            //instance = new ParcelProtectionPolicyResponseShipperInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ParcelProtectionPolicyResponseShipperInfo
        /// </summary>
        [Test]
        public void ParcelProtectionPolicyResponseShipperInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ParcelProtectionPolicyResponseShipperInfo
            //Assert.IsInstanceOf(typeof(ParcelProtectionPolicyResponseShipperInfo), instance);
        }


        /// <summary>
        /// Test the property 'ShipperID'
        /// </summary>
        [Test]
        public void ShipperIDTest()
        {
            // TODO unit test for the property 'ShipperID'
        }
        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Test]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }
        /// <summary>
        /// Test the property 'MiddleName'
        /// </summary>
        [Test]
        public void MiddleNameTest()
        {
            // TODO unit test for the property 'MiddleName'
        }
        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Test]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }
        /// <summary>
        /// Test the property 'Company'
        /// </summary>
        [Test]
        public void CompanyTest()
        {
            // TODO unit test for the property 'Company'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'PhoneNumber1'
        /// </summary>
        [Test]
        public void PhoneNumber1Test()
        {
            // TODO unit test for the property 'PhoneNumber1'
        }
        /// <summary>
        /// Test the property 'PhoneNumber2'
        /// </summary>
        [Test]
        public void PhoneNumber2Test()
        {
            // TODO unit test for the property 'PhoneNumber2'
        }
        /// <summary>
        /// Test the property 'FaxNumber'
        /// </summary>
        [Test]
        public void FaxNumberTest()
        {
            // TODO unit test for the property 'FaxNumber'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Test]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }

    }

}
