/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing ParcelProtectionCreateRequestShipmentInfoParcelInfoCommodityList
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ParcelProtectionCreateRequestShipmentInfoParcelInfoCommodityListTests
    {
        // TODO uncomment below to declare an instance variable for ParcelProtectionCreateRequestShipmentInfoParcelInfoCommodityList
        //private ParcelProtectionCreateRequestShipmentInfoParcelInfoCommodityList instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ParcelProtectionCreateRequestShipmentInfoParcelInfoCommodityList
            //instance = new ParcelProtectionCreateRequestShipmentInfoParcelInfoCommodityList();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ParcelProtectionCreateRequestShipmentInfoParcelInfoCommodityList
        /// </summary>
        [Test]
        public void ParcelProtectionCreateRequestShipmentInfoParcelInfoCommodityListInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ParcelProtectionCreateRequestShipmentInfoParcelInfoCommodityList
            //Assert.IsInstanceOf(typeof(ParcelProtectionCreateRequestShipmentInfoParcelInfoCommodityList), instance);
        }


        /// <summary>
        /// Test the property 'CategoryPath'
        /// </summary>
        [Test]
        public void CategoryPathTest()
        {
            // TODO unit test for the property 'CategoryPath'
        }
        /// <summary>
        /// Test the property 'ItemCode'
        /// </summary>
        [Test]
        public void ItemCodeTest()
        {
            // TODO unit test for the property 'ItemCode'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

    }

}
