/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing ParcelProtectionCreateRequestShipmentInfoShipperInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ParcelProtectionCreateRequestShipmentInfoShipperInfoTests
    {
        // TODO uncomment below to declare an instance variable for ParcelProtectionCreateRequestShipmentInfoShipperInfo
        //private ParcelProtectionCreateRequestShipmentInfoShipperInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ParcelProtectionCreateRequestShipmentInfoShipperInfo
            //instance = new ParcelProtectionCreateRequestShipmentInfoShipperInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ParcelProtectionCreateRequestShipmentInfoShipperInfo
        /// </summary>
        [Test]
        public void ParcelProtectionCreateRequestShipmentInfoShipperInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ParcelProtectionCreateRequestShipmentInfoShipperInfo
            //Assert.IsInstanceOf(typeof(ParcelProtectionCreateRequestShipmentInfoShipperInfo), instance);
        }


        /// <summary>
        /// Test the property 'ShipperID'
        /// </summary>
        [Test]
        public void ShipperIDTest()
        {
            // TODO unit test for the property 'ShipperID'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Test]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'CompanyName'
        /// </summary>
        [Test]
        public void CompanyNameTest()
        {
            // TODO unit test for the property 'CompanyName'
        }
        /// <summary>
        /// Test the property 'FamilyName'
        /// </summary>
        [Test]
        public void FamilyNameTest()
        {
            // TODO unit test for the property 'FamilyName'
        }
        /// <summary>
        /// Test the property 'GivenName'
        /// </summary>
        [Test]
        public void GivenNameTest()
        {
            // TODO unit test for the property 'GivenName'
        }
        /// <summary>
        /// Test the property 'MiddleName'
        /// </summary>
        [Test]
        public void MiddleNameTest()
        {
            // TODO unit test for the property 'MiddleName'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'PhoneNumbers'
        /// </summary>
        [Test]
        public void PhoneNumbersTest()
        {
            // TODO unit test for the property 'PhoneNumbers'
        }

    }

}
