/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing PrerequisiteRules
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PrerequisiteRulesTests
    {
        // TODO uncomment below to declare an instance variable for PrerequisiteRules
        //private PrerequisiteRules instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PrerequisiteRules
            //instance = new PrerequisiteRules();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PrerequisiteRules
        /// </summary>
        [Test]
        public void PrerequisiteRulesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" PrerequisiteRules
            //Assert.IsInstanceOf(typeof(PrerequisiteRules), instance);
        }


        /// <summary>
        /// Test the property 'SpecialServiceCodes'
        /// </summary>
        [Test]
        public void SpecialServiceCodesTest()
        {
            // TODO unit test for the property 'SpecialServiceCodes'
        }
        /// <summary>
        /// Test the property 'MinInputValue'
        /// </summary>
        [Test]
        public void MinInputValueTest()
        {
            // TODO unit test for the property 'MinInputValue'
        }

    }

}
