/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing RadioNuclideDetail
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RadioNuclideDetailTests
    {
        // TODO uncomment below to declare an instance variable for RadioNuclideDetail
        //private RadioNuclideDetail instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RadioNuclideDetail
            //instance = new RadioNuclideDetail();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RadioNuclideDetail
        /// </summary>
        [Test]
        public void RadioNuclideDetailInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" RadioNuclideDetail
            //Assert.IsInstanceOf(typeof(RadioNuclideDetail), instance);
        }


        /// <summary>
        /// Test the property 'ChemicalForm'
        /// </summary>
        [Test]
        public void ChemicalFormTest()
        {
            // TODO unit test for the property 'ChemicalForm'
        }
        /// <summary>
        /// Test the property 'ExpectedPackageReportableQuantity'
        /// </summary>
        [Test]
        public void ExpectedPackageReportableQuantityTest()
        {
            // TODO unit test for the property 'ExpectedPackageReportableQuantity'
        }
        /// <summary>
        /// Test the property 'PhysicalForm'
        /// </summary>
        [Test]
        public void PhysicalFormTest()
        {
            // TODO unit test for the property 'PhysicalForm'
        }
        /// <summary>
        /// Test the property 'RadioNuclide'
        /// </summary>
        [Test]
        public void RadioNuclideTest()
        {
            // TODO unit test for the property 'RadioNuclide'
        }
        /// <summary>
        /// Test the property 'RadioNuclideActivityUOM'
        /// </summary>
        [Test]
        public void RadioNuclideActivityUOMTest()
        {
            // TODO unit test for the property 'RadioNuclideActivityUOM'
        }
        /// <summary>
        /// Test the property 'RadioNuclideActivityValue'
        /// </summary>
        [Test]
        public void RadioNuclideActivityValueTest()
        {
            // TODO unit test for the property 'RadioNuclideActivityValue'
        }

    }

}
