/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing RadioActivityDetail
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RadioActivityDetailTests
    {
        // TODO uncomment below to declare an instance variable for RadioActivityDetail
        //private RadioActivityDetail instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RadioActivityDetail
            //instance = new RadioActivityDetail();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RadioActivityDetail
        /// </summary>
        [Test]
        public void RadioActivityDetailInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" RadioActivityDetail
            //Assert.IsInstanceOf(typeof(RadioActivityDetail), instance);
        }


        /// <summary>
        /// Test the property 'CriticalitySafetyIndex'
        /// </summary>
        [Test]
        public void CriticalitySafetyIndexTest()
        {
            // TODO unit test for the property 'CriticalitySafetyIndex'
        }
        /// <summary>
        /// Test the property 'RadioActiveParcelDimension'
        /// </summary>
        [Test]
        public void RadioActiveParcelDimensionTest()
        {
            // TODO unit test for the property 'RadioActiveParcelDimension'
        }
        /// <summary>
        /// Test the property 'SurfaceReading'
        /// </summary>
        [Test]
        public void SurfaceReadingTest()
        {
            // TODO unit test for the property 'SurfaceReading'
        }
        /// <summary>
        /// Test the property 'TransportIndex'
        /// </summary>
        [Test]
        public void TransportIndexTest()
        {
            // TODO unit test for the property 'TransportIndex'
        }

    }

}
