/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing Rate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RateTests
    {
        // TODO uncomment below to declare an instance variable for Rate
        //private Rate instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Rate
            //instance = new Rate();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Rate
        /// </summary>
        [Test]
        public void RateInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" Rate
            //Assert.IsInstanceOf(typeof(Rate), instance);
        }


        /// <summary>
        /// Test the property 'AlternateBaseCharge'
        /// </summary>
        [Test]
        public void AlternateBaseChargeTest()
        {
            // TODO unit test for the property 'AlternateBaseCharge'
        }
        /// <summary>
        /// Test the property 'AlternateTotalCharge'
        /// </summary>
        [Test]
        public void AlternateTotalChargeTest()
        {
            // TODO unit test for the property 'AlternateTotalCharge'
        }
        /// <summary>
        /// Test the property 'BaseCharge'
        /// </summary>
        [Test]
        public void BaseChargeTest()
        {
            // TODO unit test for the property 'BaseCharge'
        }
        /// <summary>
        /// Test the property 'BaseChargeTaxes'
        /// </summary>
        [Test]
        public void BaseChargeTaxesTest()
        {
            // TODO unit test for the property 'BaseChargeTaxes'
        }
        /// <summary>
        /// Test the property 'Carrier'
        /// </summary>
        [Test]
        public void CarrierTest()
        {
            // TODO unit test for the property 'Carrier'
        }
        /// <summary>
        /// Test the property 'CurrencyCode'
        /// </summary>
        [Test]
        public void CurrencyCodeTest()
        {
            // TODO unit test for the property 'CurrencyCode'
        }
        /// <summary>
        /// Test the property 'DeliveryCommitment'
        /// </summary>
        [Test]
        public void DeliveryCommitmentTest()
        {
            // TODO unit test for the property 'DeliveryCommitment'
        }
        /// <summary>
        /// Test the property 'DestinationZone'
        /// </summary>
        [Test]
        public void DestinationZoneTest()
        {
            // TODO unit test for the property 'DestinationZone'
        }
        /// <summary>
        /// Test the property 'DimensionalWeight'
        /// </summary>
        [Test]
        public void DimensionalWeightTest()
        {
            // TODO unit test for the property 'DimensionalWeight'
        }
        /// <summary>
        /// Test the property 'Discounts'
        /// </summary>
        [Test]
        public void DiscountsTest()
        {
            // TODO unit test for the property 'Discounts'
        }
        /// <summary>
        /// Test the property 'InductionPostalCode'
        /// </summary>
        [Test]
        public void InductionPostalCodeTest()
        {
            // TODO unit test for the property 'InductionPostalCode'
        }
        /// <summary>
        /// Test the property 'ParcelType'
        /// </summary>
        [Test]
        public void ParcelTypeTest()
        {
            // TODO unit test for the property 'ParcelType'
        }
        /// <summary>
        /// Test the property 'RateTypeId'
        /// </summary>
        [Test]
        public void RateTypeIdTest()
        {
            // TODO unit test for the property 'RateTypeId'
        }
        /// <summary>
        /// Test the property 'ServiceId'
        /// </summary>
        [Test]
        public void ServiceIdTest()
        {
            // TODO unit test for the property 'ServiceId'
        }
        /// <summary>
        /// Test the property 'SpecialServices'
        /// </summary>
        [Test]
        public void SpecialServicesTest()
        {
            // TODO unit test for the property 'SpecialServices'
        }
        /// <summary>
        /// Test the property 'Surcharges'
        /// </summary>
        [Test]
        public void SurchargesTest()
        {
            // TODO unit test for the property 'Surcharges'
        }
        /// <summary>
        /// Test the property 'TotalCarrierCharge'
        /// </summary>
        [Test]
        public void TotalCarrierChargeTest()
        {
            // TODO unit test for the property 'TotalCarrierCharge'
        }
        /// <summary>
        /// Test the property 'TotalTaxAmount'
        /// </summary>
        [Test]
        public void TotalTaxAmountTest()
        {
            // TODO unit test for the property 'TotalTaxAmount'
        }

    }

}
