/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing RealTransactionDetailReport
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RealTransactionDetailReportTests
    {
        // TODO uncomment below to declare an instance variable for RealTransactionDetailReport
        //private RealTransactionDetailReport instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RealTransactionDetailReport
            //instance = new RealTransactionDetailReport();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RealTransactionDetailReport
        /// </summary>
        [Test]
        public void RealTransactionDetailReportInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" RealTransactionDetailReport
            //Assert.IsInstanceOf(typeof(RealTransactionDetailReport), instance);
        }


        /// <summary>
        /// Test the property 'AdjustmentReason'
        /// </summary>
        [Test]
        public void AdjustmentReasonTest()
        {
            // TODO unit test for the property 'AdjustmentReason'
        }
        /// <summary>
        /// Test the property 'CreditCardFee'
        /// </summary>
        [Test]
        public void CreditCardFeeTest()
        {
            // TODO unit test for the property 'CreditCardFee'
        }
        /// <summary>
        /// Test the property 'CustomMessage1'
        /// </summary>
        [Test]
        public void CustomMessage1Test()
        {
            // TODO unit test for the property 'CustomMessage1'
        }
        /// <summary>
        /// Test the property 'CustomMessage2'
        /// </summary>
        [Test]
        public void CustomMessage2Test()
        {
            // TODO unit test for the property 'CustomMessage2'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'DestinationAddress'
        /// </summary>
        [Test]
        public void DestinationAddressTest()
        {
            // TODO unit test for the property 'DestinationAddress'
        }
        /// <summary>
        /// Test the property 'DestinationCountry'
        /// </summary>
        [Test]
        public void DestinationCountryTest()
        {
            // TODO unit test for the property 'DestinationCountry'
        }
        /// <summary>
        /// Test the property 'DestinationZip'
        /// </summary>
        [Test]
        public void DestinationZipTest()
        {
            // TODO unit test for the property 'DestinationZip'
        }
        /// <summary>
        /// Test the property 'DeveloperId'
        /// </summary>
        [Test]
        public void DeveloperIdTest()
        {
            // TODO unit test for the property 'DeveloperId'
        }
        /// <summary>
        /// Test the property 'DeveloperName'
        /// </summary>
        [Test]
        public void DeveloperNameTest()
        {
            // TODO unit test for the property 'DeveloperName'
        }
        /// <summary>
        /// Test the property 'DeveloperPostagePaymentAccountBalance'
        /// </summary>
        [Test]
        public void DeveloperPostagePaymentAccountBalanceTest()
        {
            // TODO unit test for the property 'DeveloperPostagePaymentAccountBalance'
        }
        /// <summary>
        /// Test the property 'DeveloperPostagePaymentMethod'
        /// </summary>
        [Test]
        public void DeveloperPostagePaymentMethodTest()
        {
            // TODO unit test for the property 'DeveloperPostagePaymentMethod'
        }
        /// <summary>
        /// Test the property 'DeveloperRateAmount'
        /// </summary>
        [Test]
        public void DeveloperRateAmountTest()
        {
            // TODO unit test for the property 'DeveloperRateAmount'
        }
        /// <summary>
        /// Test the property 'DeveloperRatePlan'
        /// </summary>
        [Test]
        public void DeveloperRatePlanTest()
        {
            // TODO unit test for the property 'DeveloperRatePlan'
        }
        /// <summary>
        /// Test the property 'DimensionalWeightOz'
        /// </summary>
        [Test]
        public void DimensionalWeightOzTest()
        {
            // TODO unit test for the property 'DimensionalWeightOz'
        }
        /// <summary>
        /// Test the property 'ExternalId'
        /// </summary>
        [Test]
        public void ExternalIdTest()
        {
            // TODO unit test for the property 'ExternalId'
        }
        /// <summary>
        /// Test the property 'InternationalCountryPriceGroup'
        /// </summary>
        [Test]
        public void InternationalCountryPriceGroupTest()
        {
            // TODO unit test for the property 'InternationalCountryPriceGroup'
        }
        /// <summary>
        /// Test the property 'LabelFee'
        /// </summary>
        [Test]
        public void LabelFeeTest()
        {
            // TODO unit test for the property 'LabelFee'
        }
        /// <summary>
        /// Test the property 'MailClass'
        /// </summary>
        [Test]
        public void MailClassTest()
        {
            // TODO unit test for the property 'MailClass'
        }
        /// <summary>
        /// Test the property 'MerchantId'
        /// </summary>
        [Test]
        public void MerchantIdTest()
        {
            // TODO unit test for the property 'MerchantId'
        }
        /// <summary>
        /// Test the property 'MerchantName'
        /// </summary>
        [Test]
        public void MerchantNameTest()
        {
            // TODO unit test for the property 'MerchantName'
        }
        /// <summary>
        /// Test the property 'MerchantPostageAccountPaymentMethod'
        /// </summary>
        [Test]
        public void MerchantPostageAccountPaymentMethodTest()
        {
            // TODO unit test for the property 'MerchantPostageAccountPaymentMethod'
        }
        /// <summary>
        /// Test the property 'MerchantRate'
        /// </summary>
        [Test]
        public void MerchantRateTest()
        {
            // TODO unit test for the property 'MerchantRate'
        }
        /// <summary>
        /// Test the property 'MerchantRatePlan'
        /// </summary>
        [Test]
        public void MerchantRatePlanTest()
        {
            // TODO unit test for the property 'MerchantRatePlan'
        }
        /// <summary>
        /// Test the property 'MeterNumber'
        /// </summary>
        [Test]
        public void MeterNumberTest()
        {
            // TODO unit test for the property 'MeterNumber'
        }
        /// <summary>
        /// Test the property 'OriginZip'
        /// </summary>
        [Test]
        public void OriginZipTest()
        {
            // TODO unit test for the property 'OriginZip'
        }
        /// <summary>
        /// Test the property 'OriginationAddress'
        /// </summary>
        [Test]
        public void OriginationAddressTest()
        {
            // TODO unit test for the property 'OriginationAddress'
        }
        /// <summary>
        /// Test the property 'PackageHeightInInches'
        /// </summary>
        [Test]
        public void PackageHeightInInchesTest()
        {
            // TODO unit test for the property 'PackageHeightInInches'
        }
        /// <summary>
        /// Test the property 'PackageLengthInInches'
        /// </summary>
        [Test]
        public void PackageLengthInInchesTest()
        {
            // TODO unit test for the property 'PackageLengthInInches'
        }
        /// <summary>
        /// Test the property 'PackageType'
        /// </summary>
        [Test]
        public void PackageTypeTest()
        {
            // TODO unit test for the property 'PackageType'
        }
        /// <summary>
        /// Test the property 'PackageTypeIndicator'
        /// </summary>
        [Test]
        public void PackageTypeIndicatorTest()
        {
            // TODO unit test for the property 'PackageTypeIndicator'
        }
        /// <summary>
        /// Test the property 'PackageWidthInInches'
        /// </summary>
        [Test]
        public void PackageWidthInInchesTest()
        {
            // TODO unit test for the property 'PackageWidthInInches'
        }
        /// <summary>
        /// Test the property 'ParcelTrackingNumber'
        /// </summary>
        [Test]
        public void ParcelTrackingNumberTest()
        {
            // TODO unit test for the property 'ParcelTrackingNumber'
        }
        /// <summary>
        /// Test the property 'PostageDepositAmount'
        /// </summary>
        [Test]
        public void PostageDepositAmountTest()
        {
            // TODO unit test for the property 'PostageDepositAmount'
        }
        /// <summary>
        /// Test the property 'PrintStatus'
        /// </summary>
        [Test]
        public void PrintStatusTest()
        {
            // TODO unit test for the property 'PrintStatus'
        }
        /// <summary>
        /// Test the property 'References'
        /// </summary>
        [Test]
        public void ReferencesTest()
        {
            // TODO unit test for the property 'References'
        }
        /// <summary>
        /// Test the property 'RefundDenialReason'
        /// </summary>
        [Test]
        public void RefundDenialReasonTest()
        {
            // TODO unit test for the property 'RefundDenialReason'
        }
        /// <summary>
        /// Test the property 'RefundRequestor'
        /// </summary>
        [Test]
        public void RefundRequestorTest()
        {
            // TODO unit test for the property 'RefundRequestor'
        }
        /// <summary>
        /// Test the property 'RefundStatus'
        /// </summary>
        [Test]
        public void RefundStatusTest()
        {
            // TODO unit test for the property 'RefundStatus'
        }
        /// <summary>
        /// Test the property 'ShipmentId'
        /// </summary>
        [Test]
        public void ShipmentIdTest()
        {
            // TODO unit test for the property 'ShipmentId'
        }
        /// <summary>
        /// Test the property 'ShipperPostagePaymentAccountBalance'
        /// </summary>
        [Test]
        public void ShipperPostagePaymentAccountBalanceTest()
        {
            // TODO unit test for the property 'ShipperPostagePaymentAccountBalance'
        }
        /// <summary>
        /// Test the property 'SpecialServices'
        /// </summary>
        [Test]
        public void SpecialServicesTest()
        {
            // TODO unit test for the property 'SpecialServices'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'TransactionDateTime'
        /// </summary>
        [Test]
        public void TransactionDateTimeTest()
        {
            // TODO unit test for the property 'TransactionDateTime'
        }
        /// <summary>
        /// Test the property 'TransactionId'
        /// </summary>
        [Test]
        public void TransactionIdTest()
        {
            // TODO unit test for the property 'TransactionId'
        }
        /// <summary>
        /// Test the property 'TransactionType'
        /// </summary>
        [Test]
        public void TransactionTypeTest()
        {
            // TODO unit test for the property 'TransactionType'
        }
        /// <summary>
        /// Test the property 'ValueOfGoods'
        /// </summary>
        [Test]
        public void ValueOfGoodsTest()
        {
            // TODO unit test for the property 'ValueOfGoods'
        }
        /// <summary>
        /// Test the property 'WeightInOunces'
        /// </summary>
        [Test]
        public void WeightInOuncesTest()
        {
            // TODO unit test for the property 'WeightInOunces'
        }
        /// <summary>
        /// Test the property 'Zone'
        /// </summary>
        [Test]
        public void ZoneTest()
        {
            // TODO unit test for the property 'Zone'
        }

    }

}
