/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing SchedulePickupPickupSummary
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SchedulePickupPickupSummaryTests
    {
        // TODO uncomment below to declare an instance variable for SchedulePickupPickupSummary
        //private SchedulePickupPickupSummary instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SchedulePickupPickupSummary
            //instance = new SchedulePickupPickupSummary();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SchedulePickupPickupSummary
        /// </summary>
        [Test]
        public void SchedulePickupPickupSummaryInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" SchedulePickupPickupSummary
            //Assert.IsInstanceOf(typeof(SchedulePickupPickupSummary), instance);
        }


        /// <summary>
        /// Test the property 'ServiceId'
        /// </summary>
        [Test]
        public void ServiceIdTest()
        {
            // TODO unit test for the property 'ServiceId'
        }
        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Test]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }
        /// <summary>
        /// Test the property 'TotalWeight'
        /// </summary>
        [Test]
        public void TotalWeightTest()
        {
            // TODO unit test for the property 'TotalWeight'
        }

    }

}
