/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing SchedulePickupResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SchedulePickupResponseTests
    {
        // TODO uncomment below to declare an instance variable for SchedulePickupResponse
        //private SchedulePickupResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SchedulePickupResponse
            //instance = new SchedulePickupResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SchedulePickupResponse
        /// </summary>
        [Test]
        public void SchedulePickupResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" SchedulePickupResponse
            //Assert.IsInstanceOf(typeof(SchedulePickupResponse), instance);
        }


        /// <summary>
        /// Test the property 'PickupAddress'
        /// </summary>
        [Test]
        public void PickupAddressTest()
        {
            // TODO unit test for the property 'PickupAddress'
        }
        /// <summary>
        /// Test the property 'Carrier'
        /// </summary>
        [Test]
        public void CarrierTest()
        {
            // TODO unit test for the property 'Carrier'
        }
        /// <summary>
        /// Test the property 'PickupSummary'
        /// </summary>
        [Test]
        public void PickupSummaryTest()
        {
            // TODO unit test for the property 'PickupSummary'
        }
        /// <summary>
        /// Test the property 'Reference'
        /// </summary>
        [Test]
        public void ReferenceTest()
        {
            // TODO unit test for the property 'Reference'
        }
        /// <summary>
        /// Test the property 'PackageLocation'
        /// </summary>
        [Test]
        public void PackageLocationTest()
        {
            // TODO unit test for the property 'PackageLocation'
        }
        /// <summary>
        /// Test the property 'SpecialInstructions'
        /// </summary>
        [Test]
        public void SpecialInstructionsTest()
        {
            // TODO unit test for the property 'SpecialInstructions'
        }
        /// <summary>
        /// Test the property 'PickupDateTime'
        /// </summary>
        [Test]
        public void PickupDateTimeTest()
        {
            // TODO unit test for the property 'PickupDateTime'
        }
        /// <summary>
        /// Test the property 'PickupConfirmationNumber'
        /// </summary>
        [Test]
        public void PickupConfirmationNumberTest()
        {
            // TODO unit test for the property 'PickupConfirmationNumber'
        }
        /// <summary>
        /// Test the property 'PickupId'
        /// </summary>
        [Test]
        public void PickupIdTest()
        {
            // TODO unit test for the property 'PickupId'
        }

    }

}
