/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing ServicesParameterRule
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ServicesParameterRuleTests
    {
        // TODO uncomment below to declare an instance variable for ServicesParameterRule
        //private ServicesParameterRule instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ServicesParameterRule
            //instance = new ServicesParameterRule();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ServicesParameterRule
        /// </summary>
        [Test]
        public void ServicesParameterRuleInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ServicesParameterRule
            //Assert.IsInstanceOf(typeof(ServicesParameterRule), instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'BrandedName'
        /// </summary>
        [Test]
        public void BrandedNameTest()
        {
            // TODO unit test for the property 'BrandedName'
        }
        /// <summary>
        /// Test the property 'Required'
        /// </summary>
        [Test]
        public void RequiredTest()
        {
            // TODO unit test for the property 'Required'
        }
        /// <summary>
        /// Test the property 'MinValue'
        /// </summary>
        [Test]
        public void MinValueTest()
        {
            // TODO unit test for the property 'MinValue'
        }
        /// <summary>
        /// Test the property 'MaxValue'
        /// </summary>
        [Test]
        public void MaxValueTest()
        {
            // TODO unit test for the property 'MaxValue'
        }
        /// <summary>
        /// Test the property 'FreeValue'
        /// </summary>
        [Test]
        public void FreeValueTest()
        {
            // TODO unit test for the property 'FreeValue'
        }
        /// <summary>
        /// Test the property 'Format'
        /// </summary>
        [Test]
        public void FormatTest()
        {
            // TODO unit test for the property 'Format'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

    }

}
