/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing Shipment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ShipmentTests
    {
        // TODO uncomment below to declare an instance variable for Shipment
        //private Shipment instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Shipment
            //instance = new Shipment();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Shipment
        /// </summary>
        [Test]
        public void ShipmentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" Shipment
            //Assert.IsInstanceOf(typeof(Shipment), instance);
        }


        /// <summary>
        /// Test the property 'AdditionalAddresses'
        /// </summary>
        [Test]
        public void AdditionalAddressesTest()
        {
            // TODO unit test for the property 'AdditionalAddresses'
        }
        /// <summary>
        /// Test the property 'AltReturnAddress'
        /// </summary>
        [Test]
        public void AltReturnAddressTest()
        {
            // TODO unit test for the property 'AltReturnAddress'
        }
        /// <summary>
        /// Test the property 'CarrierPayments'
        /// </summary>
        [Test]
        public void CarrierPaymentsTest()
        {
            // TODO unit test for the property 'CarrierPayments'
        }
        /// <summary>
        /// Test the property 'Customs'
        /// </summary>
        [Test]
        public void CustomsTest()
        {
            // TODO unit test for the property 'Customs'
        }
        /// <summary>
        /// Test the property 'Documents'
        /// </summary>
        [Test]
        public void DocumentsTest()
        {
            // TODO unit test for the property 'Documents'
        }
        /// <summary>
        /// Test the property 'FromAddress'
        /// </summary>
        [Test]
        public void FromAddressTest()
        {
            // TODO unit test for the property 'FromAddress'
        }
        /// <summary>
        /// Test the property 'HazmatDetails'
        /// </summary>
        [Test]
        public void HazmatDetailsTest()
        {
            // TODO unit test for the property 'HazmatDetails'
        }
        /// <summary>
        /// Test the property 'Parcel'
        /// </summary>
        [Test]
        public void ParcelTest()
        {
            // TODO unit test for the property 'Parcel'
        }
        /// <summary>
        /// Test the property 'ParcelTrackingNumber'
        /// </summary>
        [Test]
        public void ParcelTrackingNumberTest()
        {
            // TODO unit test for the property 'ParcelTrackingNumber'
        }
        /// <summary>
        /// Test the property 'Rates'
        /// </summary>
        [Test]
        public void RatesTest()
        {
            // TODO unit test for the property 'Rates'
        }
        /// <summary>
        /// Test the property 'References'
        /// </summary>
        [Test]
        public void ReferencesTest()
        {
            // TODO unit test for the property 'References'
        }
        /// <summary>
        /// Test the property 'ShipmentId'
        /// </summary>
        [Test]
        public void ShipmentIdTest()
        {
            // TODO unit test for the property 'ShipmentId'
        }
        /// <summary>
        /// Test the property 'ShipmentOptions'
        /// </summary>
        [Test]
        public void ShipmentOptionsTest()
        {
            // TODO unit test for the property 'ShipmentOptions'
        }
        /// <summary>
        /// Test the property 'ShipmentType'
        /// </summary>
        [Test]
        public void ShipmentTypeTest()
        {
            // TODO unit test for the property 'ShipmentType'
        }
        /// <summary>
        /// Test the property 'SoldToAddress'
        /// </summary>
        [Test]
        public void SoldToAddressTest()
        {
            // TODO unit test for the property 'SoldToAddress'
        }
        /// <summary>
        /// Test the property 'ToAddress'
        /// </summary>
        [Test]
        public void ToAddressTest()
        {
            // TODO unit test for the property 'ToAddress'
        }

    }

}
