/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing Signatory
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SignatoryTests
    {
        // TODO uncomment below to declare an instance variable for Signatory
        //private Signatory instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Signatory
            //instance = new Signatory();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Signatory
        /// </summary>
        [Test]
        public void SignatoryInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" Signatory
            //Assert.IsInstanceOf(typeof(Signatory), instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Place'
        /// </summary>
        [Test]
        public void PlaceTest()
        {
            // TODO unit test for the property 'Place'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

    }

}
