/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing SpecialService
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SpecialServiceTests
    {
        // TODO uncomment below to declare an instance variable for SpecialService
        //private SpecialService instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SpecialService
            //instance = new SpecialService();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SpecialService
        /// </summary>
        [Test]
        public void SpecialServiceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" SpecialService
            //Assert.IsInstanceOf(typeof(SpecialService), instance);
        }


        /// <summary>
        /// Test the property 'Fee'
        /// </summary>
        [Test]
        public void FeeTest()
        {
            // TODO unit test for the property 'Fee'
        }
        /// <summary>
        /// Test the property 'InputParameters'
        /// </summary>
        [Test]
        public void InputParametersTest()
        {
            // TODO unit test for the property 'InputParameters'
        }
        /// <summary>
        /// Test the property 'SpecialServiceId'
        /// </summary>
        [Test]
        public void SpecialServiceIdTest()
        {
            // TODO unit test for the property 'SpecialServiceId'
        }

    }

}
