/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing SpecialServicesRule
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SpecialServicesRuleTests
    {
        // TODO uncomment below to declare an instance variable for SpecialServicesRule
        //private SpecialServicesRule instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SpecialServicesRule
            //instance = new SpecialServicesRule();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SpecialServicesRule
        /// </summary>
        [Test]
        public void SpecialServicesRuleInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" SpecialServicesRule
            //Assert.IsInstanceOf(typeof(SpecialServicesRule), instance);
        }


        /// <summary>
        /// Test the property 'SpecialServiceId'
        /// </summary>
        [Test]
        public void SpecialServiceIdTest()
        {
            // TODO unit test for the property 'SpecialServiceId'
        }
        /// <summary>
        /// Test the property 'BrandedName'
        /// </summary>
        [Test]
        public void BrandedNameTest()
        {
            // TODO unit test for the property 'BrandedName'
        }
        /// <summary>
        /// Test the property 'CategoryId'
        /// </summary>
        [Test]
        public void CategoryIdTest()
        {
            // TODO unit test for the property 'CategoryId'
        }
        /// <summary>
        /// Test the property 'CategoryName'
        /// </summary>
        [Test]
        public void CategoryNameTest()
        {
            // TODO unit test for the property 'CategoryName'
        }
        /// <summary>
        /// Test the property 'Trackable'
        /// </summary>
        [Test]
        public void TrackableTest()
        {
            // TODO unit test for the property 'Trackable'
        }
        /// <summary>
        /// Test the property 'InputParameterRules'
        /// </summary>
        [Test]
        public void InputParameterRulesTest()
        {
            // TODO unit test for the property 'InputParameterRules'
        }
        /// <summary>
        /// Test the property 'PrerequisiteRules'
        /// </summary>
        [Test]
        public void PrerequisiteRulesTest()
        {
            // TODO unit test for the property 'PrerequisiteRules'
        }
        /// <summary>
        /// Test the property 'IncompatibleSpecialServices'
        /// </summary>
        [Test]
        public void IncompatibleSpecialServicesTest()
        {
            // TODO unit test for the property 'IncompatibleSpecialServices'
        }

    }

}
