/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing TrackingAddress
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TrackingAddressTests
    {
        // TODO uncomment below to declare an instance variable for TrackingAddress
        //private TrackingAddress instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TrackingAddress
            //instance = new TrackingAddress();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TrackingAddress
        /// </summary>
        [Test]
        public void TrackingAddressInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" TrackingAddress
            //Assert.IsInstanceOf(typeof(TrackingAddress), instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Address1'
        /// </summary>
        [Test]
        public void Address1Test()
        {
            // TODO unit test for the property 'Address1'
        }
        /// <summary>
        /// Test the property 'Address2'
        /// </summary>
        [Test]
        public void Address2Test()
        {
            // TODO unit test for the property 'Address2'
        }
        /// <summary>
        /// Test the property 'Address3'
        /// </summary>
        [Test]
        public void Address3Test()
        {
            // TODO unit test for the property 'Address3'
        }
        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Test]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }
        /// <summary>
        /// Test the property 'StateOrProvince'
        /// </summary>
        [Test]
        public void StateOrProvinceTest()
        {
            // TODO unit test for the property 'StateOrProvince'
        }
        /// <summary>
        /// Test the property 'PostalCode'
        /// </summary>
        [Test]
        public void PostalCodeTest()
        {
            // TODO unit test for the property 'PostalCode'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Test]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }

    }

}
