/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing TrackingResponseScanDetailsList
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TrackingResponseScanDetailsListTests
    {
        // TODO uncomment below to declare an instance variable for TrackingResponseScanDetailsList
        //private TrackingResponseScanDetailsList instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TrackingResponseScanDetailsList
            //instance = new TrackingResponseScanDetailsList();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TrackingResponseScanDetailsList
        /// </summary>
        [Test]
        public void TrackingResponseScanDetailsListInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" TrackingResponseScanDetailsList
            //Assert.IsInstanceOf(typeof(TrackingResponseScanDetailsList), instance);
        }


        /// <summary>
        /// Test the property 'EventDate'
        /// </summary>
        [Test]
        public void EventDateTest()
        {
            // TODO unit test for the property 'EventDate'
        }
        /// <summary>
        /// Test the property 'EventTime'
        /// </summary>
        [Test]
        public void EventTimeTest()
        {
            // TODO unit test for the property 'EventTime'
        }
        /// <summary>
        /// Test the property 'EventCity'
        /// </summary>
        [Test]
        public void EventCityTest()
        {
            // TODO unit test for the property 'EventCity'
        }
        /// <summary>
        /// Test the property 'EventStateOrProvince'
        /// </summary>
        [Test]
        public void EventStateOrProvinceTest()
        {
            // TODO unit test for the property 'EventStateOrProvince'
        }
        /// <summary>
        /// Test the property 'PostalCode'
        /// </summary>
        [Test]
        public void PostalCodeTest()
        {
            // TODO unit test for the property 'PostalCode'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Test]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }
        /// <summary>
        /// Test the property 'ScanType'
        /// </summary>
        [Test]
        public void ScanTypeTest()
        {
            // TODO unit test for the property 'ScanType'
        }
        /// <summary>
        /// Test the property 'ScanDescription'
        /// </summary>
        [Test]
        public void ScanDescriptionTest()
        {
            // TODO unit test for the property 'ScanDescription'
        }
        /// <summary>
        /// Test the property 'PackageStatus'
        /// </summary>
        [Test]
        public void PackageStatusTest()
        {
            // TODO unit test for the property 'PackageStatus'
        }

    }

}
