/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing TrackingResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TrackingResponseTests
    {
        // TODO uncomment below to declare an instance variable for TrackingResponse
        //private TrackingResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TrackingResponse
            //instance = new TrackingResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TrackingResponse
        /// </summary>
        [Test]
        public void TrackingResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" TrackingResponse
            //Assert.IsInstanceOf(typeof(TrackingResponse), instance);
        }


        /// <summary>
        /// Test the property 'PackageCount'
        /// </summary>
        [Test]
        public void PackageCountTest()
        {
            // TODO unit test for the property 'PackageCount'
        }
        /// <summary>
        /// Test the property 'Carrier'
        /// </summary>
        [Test]
        public void CarrierTest()
        {
            // TODO unit test for the property 'Carrier'
        }
        /// <summary>
        /// Test the property 'TrackingNumber'
        /// </summary>
        [Test]
        public void TrackingNumberTest()
        {
            // TODO unit test for the property 'TrackingNumber'
        }
        /// <summary>
        /// Test the property 'ReferenceNumber'
        /// </summary>
        [Test]
        public void ReferenceNumberTest()
        {
            // TODO unit test for the property 'ReferenceNumber'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'UpdatedDate'
        /// </summary>
        [Test]
        public void UpdatedDateTest()
        {
            // TODO unit test for the property 'UpdatedDate'
        }
        /// <summary>
        /// Test the property 'UpdatedTime'
        /// </summary>
        [Test]
        public void UpdatedTimeTest()
        {
            // TODO unit test for the property 'UpdatedTime'
        }
        /// <summary>
        /// Test the property 'ShipDate'
        /// </summary>
        [Test]
        public void ShipDateTest()
        {
            // TODO unit test for the property 'ShipDate'
        }
        /// <summary>
        /// Test the property 'EstimatedDeliveryDate'
        /// </summary>
        [Test]
        public void EstimatedDeliveryDateTest()
        {
            // TODO unit test for the property 'EstimatedDeliveryDate'
        }
        /// <summary>
        /// Test the property 'EstimatedDeliveryTime'
        /// </summary>
        [Test]
        public void EstimatedDeliveryTimeTest()
        {
            // TODO unit test for the property 'EstimatedDeliveryTime'
        }
        /// <summary>
        /// Test the property 'DeliveryDate'
        /// </summary>
        [Test]
        public void DeliveryDateTest()
        {
            // TODO unit test for the property 'DeliveryDate'
        }
        /// <summary>
        /// Test the property 'DeliveryTime'
        /// </summary>
        [Test]
        public void DeliveryTimeTest()
        {
            // TODO unit test for the property 'DeliveryTime'
        }
        /// <summary>
        /// Test the property 'DeliveryLocation'
        /// </summary>
        [Test]
        public void DeliveryLocationTest()
        {
            // TODO unit test for the property 'DeliveryLocation'
        }
        /// <summary>
        /// Test the property 'DeliveryLocationDescription'
        /// </summary>
        [Test]
        public void DeliveryLocationDescriptionTest()
        {
            // TODO unit test for the property 'DeliveryLocationDescription'
        }
        /// <summary>
        /// Test the property 'SignedBy'
        /// </summary>
        [Test]
        public void SignedByTest()
        {
            // TODO unit test for the property 'SignedBy'
        }
        /// <summary>
        /// Test the property 'Weight'
        /// </summary>
        [Test]
        public void WeightTest()
        {
            // TODO unit test for the property 'Weight'
        }
        /// <summary>
        /// Test the property 'WeightOUM'
        /// </summary>
        [Test]
        public void WeightOUMTest()
        {
            // TODO unit test for the property 'WeightOUM'
        }
        /// <summary>
        /// Test the property 'ReattemptDate'
        /// </summary>
        [Test]
        public void ReattemptDateTest()
        {
            // TODO unit test for the property 'ReattemptDate'
        }
        /// <summary>
        /// Test the property 'ReattemptTime'
        /// </summary>
        [Test]
        public void ReattemptTimeTest()
        {
            // TODO unit test for the property 'ReattemptTime'
        }
        /// <summary>
        /// Test the property 'DestinationAddress'
        /// </summary>
        [Test]
        public void DestinationAddressTest()
        {
            // TODO unit test for the property 'DestinationAddress'
        }
        /// <summary>
        /// Test the property 'SenderAddress'
        /// </summary>
        [Test]
        public void SenderAddressTest()
        {
            // TODO unit test for the property 'SenderAddress'
        }
        /// <summary>
        /// Test the property 'ScanDetailsList'
        /// </summary>
        [Test]
        public void ScanDetailsListTest()
        {
            // TODO unit test for the property 'ScanDetailsList'
        }

    }

}
