/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing VoidParcelProtectionRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VoidParcelProtectionRequestTests
    {
        // TODO uncomment below to declare an instance variable for VoidParcelProtectionRequest
        //private VoidParcelProtectionRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of VoidParcelProtectionRequest
            //instance = new VoidParcelProtectionRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of VoidParcelProtectionRequest
        /// </summary>
        [Test]
        public void VoidParcelProtectionRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" VoidParcelProtectionRequest
            //Assert.IsInstanceOf(typeof(VoidParcelProtectionRequest), instance);
        }


        /// <summary>
        /// Test the property 'ShipperID'
        /// </summary>
        [Test]
        public void ShipperIDTest()
        {
            // TODO unit test for the property 'ShipperID'
        }
        /// <summary>
        /// Test the property 'ParcelProtectionAccountID'
        /// </summary>
        [Test]
        public void ParcelProtectionAccountIDTest()
        {
            // TODO unit test for the property 'ParcelProtectionAccountID'
        }

    }

}
