/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using shippingapi.Api;
using shippingapi.Model;
using shippingapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing WeightRules
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WeightRulesTests
    {
        // TODO uncomment below to declare an instance variable for WeightRules
        //private WeightRules instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WeightRules
            //instance = new WeightRules();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WeightRules
        /// </summary>
        [Test]
        public void WeightRulesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" WeightRules
            //Assert.IsInstanceOf(typeof(WeightRules), instance);
        }


        /// <summary>
        /// Test the property 'Required'
        /// </summary>
        [Test]
        public void RequiredTest()
        {
            // TODO unit test for the property 'Required'
        }
        /// <summary>
        /// Test the property 'UnitOfMeasurement'
        /// </summary>
        [Test]
        public void UnitOfMeasurementTest()
        {
            // TODO unit test for the property 'UnitOfMeasurement'
        }
        /// <summary>
        /// Test the property 'MinWeight'
        /// </summary>
        [Test]
        public void MinWeightTest()
        {
            // TODO unit test for the property 'MinWeight'
        }
        /// <summary>
        /// Test the property 'MaxWeight'
        /// </summary>
        [Test]
        public void MaxWeightTest()
        {
            // TODO unit test for the property 'MaxWeight'
        }

    }

}
