/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using shippingapi.Client;
using shippingapi.Api;
using shippingapi.Model;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing CarrierInfoApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class CarrierInfoApiTests
    {
        private CarrierInfoApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new CarrierInfoApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CarrierInfoApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' CarrierInfoApi
            //Assert.IsInstanceOf(typeof(CarrierInfoApi), instance);
        }

        
        /// <summary>
        /// Test GetCarrierFacilities
        /// </summary>
        [Test]
        public void GetCarrierFacilitiesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CarrierFacilityRequest carrierFacilityRequest = null;
            //bool? xPBUnifiedErrorStructure = null;
            //var response = instance.GetCarrierFacilities(carrierFacilityRequest, xPBUnifiedErrorStructure);
            //Assert.IsInstanceOf(typeof(CarrierFacilityResponse), response, "response is CarrierFacilityResponse");
        }
        
        /// <summary>
        /// Test GetCarrierLicenseAgreement
        /// </summary>
        [Test]
        public void GetCarrierLicenseAgreementTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string carrier = null;
            //ISOCountryCode originCountryCode = null;
            //bool? xPBUnifiedErrorStructure = null;
            //var response = instance.GetCarrierLicenseAgreement(carrier, originCountryCode, xPBUnifiedErrorStructure);
            //Assert.IsInstanceOf(typeof(InlineResponse200), response, "response is InlineResponse200");
        }
        
        /// <summary>
        /// Test GetCarrierServiceRules
        /// </summary>
        [Test]
        public void GetCarrierServiceRulesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Carrier carrier = null;
            //ISOCountryCode originCountryCode = null;
            //ISOCountryCode destinationCountryCode = null;
            //bool? xPBUnifiedErrorStructure = null;
            //string rateTypeId = null;
            //string futureShipmentDate = null;
            //DateTime? returnShipment = null;
            //bool? compactResponse = null;
            //var response = instance.GetCarrierServiceRules(carrier, originCountryCode, destinationCountryCode, xPBUnifiedErrorStructure, rateTypeId, futureShipmentDate, returnShipment, compactResponse);
            //Assert.IsInstanceOf(typeof(CarrierRule), response, "response is CarrierRule");
        }
        
        /// <summary>
        /// Test GetCarrierSupportedDestination
        /// </summary>
        [Test]
        public void GetCarrierSupportedDestinationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Carrier carrier = null;
            //ISOCountryCode originCountryCode = null;
            //bool? xPBUnifiedErrorStructure = null;
            //var response = instance.GetCarrierSupportedDestination(carrier, originCountryCode, xPBUnifiedErrorStructure);
            //Assert.IsInstanceOf(typeof(List<Object>), response, "response is List<Object>");
        }
        
    }

}
