/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using shippingapi.Client;
using shippingapi.Api;
using shippingapi.Model;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing CrossBorderQuotesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class CrossBorderQuotesApiTests
    {
        private CrossBorderQuotesApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new CrossBorderQuotesApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CrossBorderQuotesApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' CrossBorderQuotesApi
            //Assert.IsInstanceOf(typeof(CrossBorderQuotesApi), instance);
        }

        
        /// <summary>
        /// Test GetCrossBorderQuotes
        /// </summary>
        [Test]
        public void GetCrossBorderQuotesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CrossBorderQuotesRequest crossBorderQuotesRequest = null;
            //bool? xPBUnifiedErrorStructure = null;
            //var response = instance.GetCrossBorderQuotes(crossBorderQuotesRequest, xPBUnifiedErrorStructure);
            //Assert.IsInstanceOf(typeof(CrossBorderQuotesResponse), response, "response is CrossBorderQuotesResponse");
        }
        
        /// <summary>
        /// Test PredictedHSCode
        /// </summary>
        [Test]
        public void PredictedHSCodeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xPBTransactionId = null;
            //Manifest manifest = null;
            //bool? xPBUnifiedErrorStructure = null;
            //var response = instance.PredictedHSCode(xPBTransactionId, manifest, xPBUnifiedErrorStructure);
            //Assert.IsInstanceOf(typeof(ParcelProtectionPolicyResponse), response, "response is ParcelProtectionPolicyResponse");
        }
        
    }

}
