/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using shippingapi.Client;
using shippingapi.Api;
using shippingapi.Model;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing PickupApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class PickupApiTests
    {
        private PickupApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new PickupApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PickupApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' PickupApi
            //Assert.IsInstanceOf(typeof(PickupApi), instance);
        }

        
        /// <summary>
        /// Test CancelPickup
        /// </summary>
        [Test]
        public void CancelPickupTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xPBTransactionId = null;
            //string pickupId = null;
            //bool? xPBUnifiedErrorStructure = null;
            //var response = instance.CancelPickup(xPBTransactionId, pickupId, xPBUnifiedErrorStructure);
            //Assert.IsInstanceOf(typeof(InlineResponse2001), response, "response is InlineResponse2001");
        }
        
        /// <summary>
        /// Test GetPickupschedule
        /// </summary>
        [Test]
        public void GetPickupscheduleTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xPBTransactionId = null;
            //SchedulePickup schedulePickup = null;
            //bool? xPBUnifiedErrorStructure = null;
            //var response = instance.GetPickupschedule(xPBTransactionId, schedulePickup, xPBUnifiedErrorStructure);
            //Assert.IsInstanceOf(typeof(SchedulePickupResponse), response, "response is SchedulePickupResponse");
        }
        
    }

}
