/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using shippingapi.Client;
using shippingapi.Api;
using shippingapi.Model;

namespace shippingapi.Test
{
    /// <summary>
    ///  Class for testing TrackingApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class TrackingApiTests
    {
        private TrackingApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new TrackingApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TrackingApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' TrackingApi
            //Assert.IsInstanceOf(typeof(TrackingApi), instance);
        }

        
        /// <summary>
        /// Test AddTrackingEvents
        /// </summary>
        [Test]
        public void AddTrackingEventsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //AddTrackingEvents addTrackingEvents = null;
            //bool? xPBUnifiedErrorStructure = null;
            //var response = instance.AddTrackingEvents(addTrackingEvents, xPBUnifiedErrorStructure);
            //Assert.IsInstanceOf(typeof(InlineResponse2002), response, "response is InlineResponse2002");
        }
        
        /// <summary>
        /// Test GetTrackingDetails
        /// </summary>
        [Test]
        public void GetTrackingDetailsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string trackingNumber = null;
            //string packageIdentifierType = null;
            //string carrier = null;
            //bool? xPBUnifiedErrorStructure = null;
            //var response = instance.GetTrackingDetails(trackingNumber, packageIdentifierType, carrier, xPBUnifiedErrorStructure);
            //Assert.IsInstanceOf(typeof(TrackingResponse), response, "response is TrackingResponse");
        }
        
    }

}
