/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;

namespace shippingapi.Client
{
    /// <summary>
    /// API Response
    /// </summary>
    public class ApiResponse<T>
    {
        /// <summary>
        /// Gets or sets the status code (HTTP status code)
        /// </summary>
        /// <value>The status code.</value>
        public int StatusCode { get; private set; }

        /// <summary>
        /// Gets or sets the HTTP headers
        /// </summary>
        /// <value>HTTP headers</value>
        public IDictionary<string, string> Headers { get; private set; }

        /// <summary>
        /// Gets or sets the data (parsed HTTP body)
        /// </summary>
        /// <value>The data.</value>
        public T Data { get; private set; }

        /// <summary>
        /// Gets or sets the raw request URL (Raw HTTP request URL)
        /// </summary>
        /// <value>The raw request.</value>
        public string HttpRequestUrl { get; private set; }

        /// <summary>
        /// Gets or sets the request headers as a string
        /// </summary>
        /// <value>The request HTTP headers.</value>
        public string HttpRequestHeaders { get; private set; }

        /// <summary>
        /// Gets or sets the raw request body (Raw HTTP request body)
        /// </summary>
        /// <value>The raw request.</value>
        public string HttpRequestBody { get; private set; }

        /// <summary>
        /// Gets or sets the raw response body (Raw HTTP response body)
        /// </summary>
        /// <value>The raw response.</value>
        public string HttpResponseBody { get; private set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="ApiResponse&lt;T&gt;" /> class.
        /// </summary>
        /// <param name="statusCode">HTTP status code.</param>
        /// <param name="headers">HTTP headers.</param>
        /// <param name="data">Data (parsed HTTP body)</param>
        /// <param name="httpRequestUrl">HTTP request URL</param>
        /// <param name="httpRequestHeaders">HTTP request headers</param>
        /// <param name="httpRequestBody">HTTP request body</param>
        /// <param name="httpResponseBody">HTTP response body</param>
        public ApiResponse(int statusCode, IDictionary<string, string> headers, T data, string httpRequestUrl = null, string httpRequestHeaders = null, string httpRequestBody = null, string httpResponseBody = null)
        {
            this.StatusCode= statusCode;
            this.Headers = headers;
            this.Data = data;
            this.HttpRequestUrl = httpRequestUrl;
            this.HttpRequestHeaders = httpRequestHeaders;
            this.HttpRequestBody = httpRequestBody;
            this.HttpResponseBody = httpResponseBody;
        }

    }

}
